//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partwise_Defect_Master_Dummy
    {
        public decimal Row_ID { get; set; }
        public string BODYSRNO { get; set; }
        public Nullable<System.DateTime> QDATE { get; set; }
        public Nullable<System.DateTime> QTIME { get; set; }
        public string SHIFT { get; set; }
        public string QDMS_STN { get; set; }
        public Nullable<decimal> Source_ID { get; set; }
        public Nullable<decimal> BuyoffCode { get; set; }
        public Nullable<decimal> Stage_ID { get; set; }
        public Nullable<decimal> Part_ID { get; set; }
        public string IND { get; set; }
        public string PART { get; set; }
        public Nullable<decimal> Defect_ID { get; set; }
        public Nullable<bool> DEFECT_STATUS { get; set; }
        public string DEFECT_CATEGORY { get; set; }
        public Nullable<decimal> Location_ID { get; set; }
        public Nullable<decimal> Severity_ID { get; set; }
        public Nullable<bool> REWORK_STATUS { get; set; }
        public Nullable<int> REWORK_DURATION { get; set; }
        public Nullable<decimal> REWORKED_BY { get; set; }
        public Nullable<System.DateTime> REWORK_DATE { get; set; }
        public string REMARKS { get; set; }
        public Nullable<decimal> Plant_ID { get; set; }
        public Nullable<decimal> Shop_ID { get; set; }
        public Nullable<decimal> Line_ID { get; set; }
        public Nullable<bool> Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public string Inserted_Host { get; set; }
        public Nullable<decimal> Inserted_User_ID { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string Updated_Host { get; set; }
        public Nullable<decimal> Updated_User_ID { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public string Inserted_HostRework { get; set; }
        public Nullable<decimal> Inserted_User_IDRework { get; set; }
        public Nullable<System.DateTime> Inserted_DateRework { get; set; }
        public string Updated_HostRework { get; set; }
        public Nullable<decimal> Updated_User_IDRework { get; set; }
        public Nullable<System.DateTime> Updated_DateRework { get; set; }
        public string VinNo { get; set; }
        public Nullable<decimal> Shift_ID { get; set; }
        public Nullable<decimal> BWT_ID { get; set; }
        public Nullable<bool> IsToModify { get; set; }
        public Nullable<bool> isAlreadySaved { get; set; }
        public Nullable<bool> isToDelete { get; set; }
        public string ModelCode { get; set; }
        public string Rework_Before { get; set; }
        public string Rework_After { get; set; }
        public string Rework_Details { get; set; }
        public Nullable<decimal> Cause_ID { get; set; }
        public Nullable<decimal> Attribute_ID { get; set; }
    }
}
