//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_Aggregate_Part_Image
    {
        public decimal Image_ID { get; set; }
        public int Part_ID { get; set; }
        public string Image_Name { get; set; }
        public string Image_Type { get; set; }
        public string Content_Type { get; set; }
        public byte[] Image_Content { get; set; }
        public Nullable<bool> Is_Transfered { get; set; }
        public Nullable<bool> Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public decimal Inserted_User_ID { get; set; }
        public System.DateTime Inserted_Date { get; set; }
        public Nullable<decimal> Updated_User_ID { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public string Inserted_Host { get; set; }
        public string Updated_Host { get; set; }
    
        public virtual RS_BIW_Part_Master RS_BIW_Part_Master { get; set; }
    }
}
