//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_AM_Operator_Change_Request
    {
        public decimal ID { get; set; }
        public decimal Row_ID { get; set; }
        public decimal Plant_ID { get; set; }
        public decimal Shop_ID { get; set; }
        public decimal Line_ID { get; set; }
        public decimal Station_ID { get; set; }
        public Nullable<decimal> Employe_ID { get; set; }
        public decimal Current_Shift_ID { get; set; }
        public decimal New_Shift_ID { get; set; }
        public int Request_Status { get; set; }
        public Nullable<System.DateTime> Allocation_Date { get; set; }
        public bool Is_Transferred { get; set; }
        public bool Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public string Inserted_Host { get; set; }
        public Nullable<decimal> Inserted_User_ID { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string Updated_Host { get; set; }
        public Nullable<decimal> Updated_User_ID { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
    
        public virtual RS_AM_Operator_Change_Request RS_AM_Operator_Change_Request1 { get; set; }
        public virtual RS_AM_Operator_Change_Request RS_AM_Operator_Change_Request2 { get; set; }
        public virtual RS_AM_Operator_Change_Request RS_AM_Operator_Change_Request11 { get; set; }
        public virtual RS_AM_Operator_Change_Request RS_AM_Operator_Change_Request3 { get; set; }
        public virtual RS_Lines RS_Lines { get; set; }
        public virtual RS_Plants RS_Plants { get; set; }
        public virtual RS_Shift RS_Shift { get; set; }
        public virtual RS_Shift RS_Shift1 { get; set; }
        public virtual RS_Shops RS_Shops { get; set; }
        public virtual RS_Stations RS_Stations { get; set; }
    }
}
