//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_AttributionType_Master
    {
        public Nullable<decimal> Plant_ID { get; set; }
        public decimal Attribution_ID { get; set; }
        public string Attribution_Type { get; set; }
        public Nullable<decimal> Sub_Assembly_ID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ToolBox { get; set; }
        public Nullable<int> ToolBox_Post { get; set; }
        public string Inserted_Host { get; set; }
        public Nullable<decimal> Inserted_User_ID { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string Updated_Host { get; set; }
        public Nullable<decimal> Updated_User_ID { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<bool> Is_Transfered { get; set; }
        public Nullable<bool> Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
    
        public virtual RS_Major_Sub_Assembly RS_Major_Sub_Assembly { get; set; }
    }
}
