//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_All_Configuration
    {
        public decimal Row_ID { get; set; }
        public string Plant_Name { get; set; }
        public string Shop_Name { get; set; }
        public string Line_Name { get; set; }
        public string Station_Name { get; set; }
        public string Shift_Name { get; set; }
        public string Token_No { get; set; }
        public string Skill_Set { get; set; }
        public string Line_Officer { get; set; }
        public string Line_Officer_Token { get; set; }
        public string Manager_Name { get; set; }
        public string Manager_Token { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string FromDay { get; set; }
        public string ToDay { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string Error_Msg { get; set; }
        public Nullable<int> Excel_No { get; set; }
        public string Setup_Name { get; set; }
    }
}
