//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_Body_Conversion
    {
        public decimal Row_ID { get; set; }
        public string Body_Sr_No { get; set; }
        public string o_Body_Sr_No { get; set; }
        public string n_Body_Sr_No { get; set; }
        public string o_Model_Code { get; set; }
        public string n_Model_Code { get; set; }
        public string o_Biw_Part_No { get; set; }
        public string n_Biw_Part_No { get; set; }
        public string o_Color { get; set; }
        public string n_Color { get; set; }
        public string o_Remarks { get; set; }
        public string n_Remarks { get; set; }
        public string Reason { get; set; }
        public bool Is_Proceed { get; set; }
        public bool Is_Model_Code { get; set; }
        public bool Is_Transferred { get; set; }
        public bool Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public string Inserted_Host { get; set; }
        public decimal Inserted_User_ID { get; set; }
        public System.DateTime Inserted_Date { get; set; }
        public string Updated_Host { get; set; }
        public Nullable<decimal> Updated_User_ID { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
    }
}
