//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_BIW_Part_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RS_BIW_Part_Master()
        {
            this.RS_Aggregate_Part_Image = new HashSet<RS_Aggregate_Part_Image>();
        }
    
        public int Row_ID { get; set; }
        public decimal Plant_ID { get; set; }
        public decimal Shop_ID { get; set; }
        public string Variant_Code { get; set; }
        public string VARIANT_DESC { get; set; }
        public Nullable<decimal> StyleCode_ID { get; set; }
        public Nullable<decimal> Sub_Assembly_ID { get; set; }
        public string LONG_DESC { get; set; }
        public string VARIANT_TYPE { get; set; }
        public string Attribution_Parameters { get; set; }
        public Nullable<decimal> Platform_ID { get; set; }
        public string Image_Name { get; set; }
        public string Image_Type { get; set; }
        public string Content_Type { get; set; }
        public byte[] Image_Content { get; set; }
        public Nullable<bool> Is_Transfered { get; set; }
        public Nullable<bool> Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public Nullable<decimal> Inserted_User_ID { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public Nullable<decimal> Updated_User_ID { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public string Inserted_Host { get; set; }
        public string Updated_Host { get; set; }
        public Nullable<long> Config_ID { get; set; }
        public string OM_Config_ID { get; set; }
        public Nullable<bool> Is_Colour_Applicable { get; set; }
        public Nullable<bool> Is_Spare { get; set; }
        public Nullable<bool> In_Use { get; set; }
        public Nullable<bool> Color_Code { get; set; }
        public Nullable<decimal> Model_Attribute_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Aggregate_Part_Image> RS_Aggregate_Part_Image { get; set; }
        public virtual RS_Major_Sub_Assembly RS_Major_Sub_Assembly { get; set; }
        public virtual RS_Model_Attribute_Master RS_Model_Attribute_Master { get; set; }
        public virtual RS_OM_Platform RS_OM_Platform { get; set; }
        public virtual RS_Plants RS_Plants { get; set; }
        public virtual RS_Serial_Number_Configuration RS_Serial_Number_Configuration { get; set; }
        public virtual RS_Shops RS_Shops { get; set; }
        public virtual RS_Style_Code RS_Style_Code { get; set; }
    }
}
