//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_Ctrl_Cylinder_Head
    {
        public decimal CH_ID { get; set; }
        public decimal Plant_ID { get; set; }
        public decimal Shop_ID { get; set; }
        public decimal Line_ID { get; set; }
        public string Machine_ID { get; set; }
        public string Serial_No { get; set; }
        public string Status { get; set; }
        public Nullable<float> Bolt1_Step1_Torque { get; set; }
        public Nullable<float> Bolt2_Step1_Torque { get; set; }
        public Nullable<float> Bolt3_Step1_Torque { get; set; }
        public Nullable<float> Bolt4_Step1_Torque { get; set; }
        public Nullable<float> Bolt5_Step1_Torque { get; set; }
        public Nullable<float> Bolt6_Step1_Torque { get; set; }
        public Nullable<float> Bolt7_Step1_Torque { get; set; }
        public Nullable<float> Bolt8_Step1_Torque { get; set; }
        public Nullable<float> Bolt9_Step1_Torque { get; set; }
        public Nullable<float> Bolt10_Step1_Torque { get; set; }
        public Nullable<float> Bolt11_Step1_Torque { get; set; }
        public Nullable<float> Bolt12_Step1_Torque { get; set; }
        public Nullable<float> Bolt13_Step1_Torque { get; set; }
        public Nullable<float> Bolt14_Step1_Torque { get; set; }
        public Nullable<float> Bolt15_Step1_Torque { get; set; }
        public Nullable<float> Bolt16_Step1_Torque { get; set; }
        public Nullable<float> Bolt1_Step2_Angle { get; set; }
        public Nullable<float> Bolt2_Step2_Angle { get; set; }
        public Nullable<float> Bolt3_Step2_Angle { get; set; }
        public Nullable<float> Bolt4_Step2_Angle { get; set; }
        public Nullable<float> Bolt5_Step2_Angle { get; set; }
        public Nullable<float> Bolt6_Step2_Angle { get; set; }
        public Nullable<float> Bolt7_Step2_Angle { get; set; }
        public Nullable<float> Bolt8_Step2_Angle { get; set; }
        public Nullable<float> Bolt9_Step2_Angle { get; set; }
        public Nullable<float> Bolt10_Step2_Angle { get; set; }
        public Nullable<float> Bolt11_Step2_Angle { get; set; }
        public Nullable<float> Bolt12_Step2_Angle { get; set; }
        public Nullable<float> Bolt13_Step2_Angle { get; set; }
        public Nullable<float> Bolt14_Step2_Angle { get; set; }
        public Nullable<float> Bolt15_Step2_Angle { get; set; }
        public Nullable<float> Bolt16_Step2_Angle { get; set; }
        public Nullable<float> Bolt1_Step2_Torque { get; set; }
        public Nullable<float> Bolt2_Step2_Torque { get; set; }
        public Nullable<float> Bolt3_Step2_Torque { get; set; }
        public Nullable<float> Bolt4_Step2_Torque { get; set; }
        public Nullable<float> Bolt5_Step2_Torque { get; set; }
        public Nullable<float> Bolt6_Step2_Torque { get; set; }
        public Nullable<float> Bolt7_Step2_Torque { get; set; }
        public Nullable<float> Bolt8_Step2_Torque { get; set; }
        public Nullable<float> Bolt9_Step2_Torque { get; set; }
        public Nullable<float> Bolt10_Step2_Torque { get; set; }
        public Nullable<float> Bolt11_Step2_Torque { get; set; }
        public Nullable<float> Bolt12_Step2_Torque { get; set; }
        public Nullable<float> Bolt13_Step2_Torque { get; set; }
        public Nullable<float> Bolt14_Step2_Torque { get; set; }
        public Nullable<float> Bolt15_Step2_Torque { get; set; }
        public Nullable<float> Bolt16_Step2_Torque { get; set; }
        public Nullable<float> Bolt1_Step3_Torque { get; set; }
        public Nullable<float> Bolt2_Step3_Torque { get; set; }
        public Nullable<float> Bolt3_Step3_Torque { get; set; }
        public Nullable<float> Bolt4_Step3_Torque { get; set; }
        public Nullable<float> Bolt5_Step3_Torque { get; set; }
        public Nullable<float> Bolt6_Step3_Torque { get; set; }
        public Nullable<float> Bolt7_Step3_Torque { get; set; }
        public Nullable<float> Bolt8_Step3_Torque { get; set; }
        public Nullable<float> Bolt9_Step3_Torque { get; set; }
        public Nullable<float> Bolt10_Step3_Torque { get; set; }
        public Nullable<float> Bolt11_Step3_Torque { get; set; }
        public Nullable<float> Bolt12_Step3_Torque { get; set; }
        public Nullable<float> Bolt13_Step3_Torque { get; set; }
        public Nullable<float> Bolt14_Step3_Torque { get; set; }
        public Nullable<float> Bolt15_Step3_Torque { get; set; }
        public Nullable<float> Bolt16_Step3_Torque { get; set; }
        public Nullable<float> Bolt1_Step3_Angle { get; set; }
        public Nullable<float> Bolt2_Step3_Angle { get; set; }
        public Nullable<float> Bolt3_Step3_Angle { get; set; }
        public Nullable<float> Bolt4_Step3_Angle { get; set; }
        public Nullable<float> Bolt5_Step3_Angle { get; set; }
        public Nullable<float> Bolt6_Step3_Angle { get; set; }
        public Nullable<float> Bolt7_Step3_Angle { get; set; }
        public Nullable<float> Bolt8_Step3_Angle { get; set; }
        public Nullable<float> Bolt9_Step3_Angle { get; set; }
        public Nullable<float> Bolt10_Step3_Angle { get; set; }
        public Nullable<float> Bolt11_Step3_Angle { get; set; }
        public Nullable<float> Bolt12_Step3_Angle { get; set; }
        public Nullable<float> Bolt13_Step3_Angle { get; set; }
        public Nullable<float> Bolt14_Step3_Angle { get; set; }
        public Nullable<float> Bolt15_Step3_Angle { get; set; }
        public Nullable<float> Bolt16_Step3_Angle { get; set; }
        public Nullable<int> Update_Counter { get; set; }
        public System.DateTime Inserted_Date { get; set; }
        public Nullable<bool> Is_Transfered { get; set; }
        public Nullable<bool> Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public Nullable<bool> Is_Rejected { get; set; }
    }
}
