//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_Ctrl_CBM_Data_Migrated
    {
        public long Row_ID { get; set; }
        public decimal CBM_ID { get; set; }
        public decimal Parameter_Value { get; set; }
        public bool Is_Processed { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public bool Is_Transfered { get; set; }
        public bool Is_Purgeable { get; set; }
    }
}
