//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_CVI_Spindle
    {
        public int SPI_ResultID { get; set; }
        public short SPI_SpindleNumber { get; set; }
        public Nullable<short> SPI_PhaseNumber { get; set; }
        public string SPI_SpindleSerialNumber { get; set; }
        public string SPI_SpindleComment { get; set; }
        public string SPI_BoltNumber { get; set; }
        public string SPI_Isagraf { get; set; }
        public Nullable<short> SPI_ErrorCode { get; set; }
        public Nullable<short> SPI_ServoDriveError { get; set; }
        public Nullable<short> SPI_ResultType { get; set; }
        public string SPI_SpindleReport { get; set; }
        public Nullable<short> SPI_TorqueAccuracy { get; set; }
        public Nullable<decimal> SPI_TorqueTarget { get; set; }
        public Nullable<decimal> SPI_TorqueMinTolerance { get; set; }
        public Nullable<decimal> SPI_TorqueMaxTolerance { get; set; }
        public Nullable<decimal> SPI_FinalTorque { get; set; }
        public Nullable<decimal> SPI_InfTorque { get; set; }
        public Nullable<decimal> SPI_SupTorque { get; set; }
        public Nullable<decimal> SPI_AngleThreshold { get; set; }
        public Nullable<short> SPI_TorqueTrend { get; set; }
        public Nullable<decimal> SPI_AngleTarget { get; set; }
        public Nullable<decimal> SPI_AngleMinTolerance { get; set; }
        public Nullable<decimal> SPI_AngleMaxTolerance { get; set; }
        public Nullable<decimal> SPI_FinalAngle { get; set; }
        public Nullable<short> SPI_AngleTrend { get; set; }
        public Nullable<decimal> SPI_TorqueRateTarget { get; set; }
        public Nullable<decimal> SPI_TorqueRateMinTolerance { get; set; }
        public Nullable<decimal> SPI_TorqueRateMaxTolerance { get; set; }
        public Nullable<decimal> SPI_FinalTorqueRate { get; set; }
        public Nullable<short> SPI_TorqueRateTrend { get; set; }
        public Nullable<decimal> SPI_MinCurrent { get; set; }
        public Nullable<decimal> SPI_MaxCurrent { get; set; }
        public Nullable<decimal> SPI_FinalCurrent { get; set; }
        public Nullable<short> SPI_CurrentTrend { get; set; }
        public Nullable<short> SPI_MonitoringType { get; set; }
        public Nullable<short> SPI_Monitoring1Trend { get; set; }
        public Nullable<short> SPI_Monitoring2Trend { get; set; }
        public bool Is_Transfered { get; set; }
        public bool Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
    }
}
