//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_Engine_Marking_Data
    {
        public decimal Row_ID { get; set; }
        public string User_Name { get; set; }
        public string Shift { get; set; }
        public string Layout_ID { get; set; }
        public string Engine_Identification_No { get; set; }
        public string Model_Code { get; set; }
        public string Model_Description { get; set; }
        public string Status { get; set; }
        public string Mode { get; set; }
        public Nullable<System.DateTime> Marking_Date { get; set; }
        public Nullable<bool> Is_Transfered { get; set; }
        public Nullable<bool> Is_Purgeable { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
    }
}
