//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_FilePath
    {
        public decimal Row_ID { get; set; }
        public Nullable<decimal> Station_ID { get; set; }
        public string FolderPath { get; set; }
        public string FilePath { get; set; }
        public bool Is_File_Deleted { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
    }
}
