//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_Hanger
    {
        public decimal Row_ID { get; set; }
        public string Hanger_No { get; set; }
        public string BodySrNo { get; set; }
        public Nullable<decimal> Inserted_User_ID { get; set; }
        public string Inserted_Host { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
    }
}
