//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_History_LineStop
    {
        public decimal Row_ID { get; set; }
        public decimal Plant_ID { get; set; }
        public decimal Shop_ID { get; set; }
        public decimal Line_ID { get; set; }
        public Nullable<decimal> Station_ID { get; set; }
        public Nullable<System.DateTime> Stop_Time { get; set; }
        public string Stop_Reason { get; set; }
        public Nullable<System.DateTime> Resume_Time { get; set; }
        public string Remarks { get; set; }
        public string Owner { get; set; }
        public Nullable<int> PrimaryOwner_Id { get; set; }
        public Nullable<int> SecondaryOwner_Id { get; set; }
        public string Line_Stop_By { get; set; }
        public string Status { get; set; }
        public Nullable<bool> isLineStop { get; set; }
        public Nullable<bool> isEmergencyCall { get; set; }
        public Nullable<bool> isHeartBit { get; set; }
        public Nullable<decimal> EFPartGroup_ID { get; set; }
        public Nullable<bool> PLC_Ack { get; set; }
        public System.DateTime Inserted_Date { get; set; }
        public bool Is_Transfered { get; set; }
        public bool Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public Nullable<bool> Is_Tracking_Record { get; set; }
        public Nullable<decimal> Shift_ID { get; set; }
    
        public virtual RS_HL_Primary_Owner RS_HL_Primary_Owner { get; set; }
        public virtual RS_HL_Secondary_Owner RS_HL_Secondary_Owner { get; set; }
        public virtual RS_Lines RS_Lines { get; set; }
        public virtual RS_Plants RS_Plants { get; set; }
        public virtual RS_Shift RS_Shift { get; set; }
        public virtual RS_Shops RS_Shops { get; set; }
        public virtual RS_Stations RS_Stations { get; set; }
    }
}
