//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_Kitting_Zone_Part
    {
        public decimal Kitting_Zone_Part_ID { get; set; }
        public decimal Kitting_Zone_ID { get; set; }
        public decimal Plant_ID { get; set; }
        public Nullable<decimal> Line_ID { get; set; }
        public decimal Shop_ID { get; set; }
        public Nullable<decimal> Station_ID { get; set; }
        public string Part_No { get; set; }
        public string Model_Code { get; set; }
        public string Part_Description { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<bool> Is_Transfered { get; set; }
        public Nullable<bool> Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public decimal Inserted_User_ID { get; set; }
        public System.DateTime Inserted_Date { get; set; }
        public Nullable<decimal> Updated_User_ID { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
    }
}
