//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_Lines
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RS_Lines()
        {
            this.RS_Abs_Operator_Transfer_Allocation = new HashSet<RS_Abs_Operator_Transfer_Allocation>();
            this.RS_Abs_Operator_Transfer_Allocation1 = new HashSet<RS_Abs_Operator_Transfer_Allocation>();
            this.RS_AM_Default_URL = new HashSet<RS_AM_Default_URL>();
            this.RS_AM_Employee_SkillSet = new HashSet<RS_AM_Employee_SkillSet>();
            this.RS_AM_LeaveManagement = new HashSet<RS_AM_LeaveManagement>();
            this.RS_AM_Line_Supervisor_Mapping = new HashSet<RS_AM_Line_Supervisor_Mapping>();
            this.RS_AM_Operator_Change_Request = new HashSet<RS_AM_Operator_Change_Request>();
            this.RS_AM_Operator_Station_Allocation = new HashSet<RS_AM_Operator_Station_Allocation>();
            this.RS_AM_Operator_Station_Allocation_History = new HashSet<RS_AM_Operator_Station_Allocation_History>();
            this.RS_AM_Operator_Station_Allocation_History1 = new HashSet<RS_AM_Operator_Station_Allocation_History>();
            this.RS_AM_Station_Operation = new HashSet<RS_AM_Station_Operation>();
            this.RS_Assign_OperatorToSupervisor = new HashSet<RS_Assign_OperatorToSupervisor>();
            this.RS_Ctrl_Alarm_Signals = new HashSet<RS_Ctrl_Alarm_Signals>();
            this.RS_Ctrl_Alarm_Signals_History = new HashSet<RS_Ctrl_Alarm_Signals_History>();
            this.RS_Ctrl_Conveyor_Signal = new HashSet<RS_Ctrl_Conveyor_Signal>();
            this.RS_Ctrl_Cyl_Head_MB_CON_Data = new HashSet<RS_Ctrl_Cyl_Head_MB_CON_Data>();
            this.RS_Ctrl_Equipment_Status = new HashSet<RS_Ctrl_Equipment_Status>();
            this.RS_Ctrl_Equipment_Status_History = new HashSet<RS_Ctrl_Equipment_Status_History>();
            this.RS_Ctrl_Leak_Testing = new HashSet<RS_Ctrl_Leak_Testing>();
            this.RS_Ctrl_Line_Stop_History = new HashSet<RS_Ctrl_Line_Stop_History>();
            this.RS_Ctrl_LineStopEmergency = new HashSet<RS_Ctrl_LineStopEmergency>();
            this.RS_Ctrl_MBCAB_CONROD = new HashSet<RS_Ctrl_MBCAB_CONROD>();
            this.RS_Ctrl_Oil_Dispencing = new HashSet<RS_Ctrl_Oil_Dispencing>();
            this.RS_Ctrl_Station_Status = new HashSet<RS_Ctrl_Station_Status>();
            this.RS_Dashboard_Master = new HashSet<RS_Dashboard_Master>();
            this.RS_Department = new HashSet<RS_Department>();
            this.RS_Error_Log = new HashSet<RS_Error_Log>();
            this.RS_External_Training_Data = new HashSet<RS_External_Training_Data>();
            this.RS_Help_Category = new HashSet<RS_Help_Category>();
            this.RS_Help_Desk = new HashSet<RS_Help_Desk>();
            this.RS_History_Line_TACT_Time = new HashSet<RS_History_Line_TACT_Time>();
            this.RS_History_LineStop = new HashSet<RS_History_LineStop>();
            this.RS_IoT_Tags = new HashSet<RS_IoT_Tags>();
            this.RS_Lock_Table = new HashSet<RS_Lock_Table>();
            this.RS_Maintenance_Machine_Part = new HashSet<RS_Maintenance_Machine_Part>();
            this.RS_Manifest = new HashSet<RS_Manifest>();
            this.RS_ManPower_Required = new HashSet<RS_ManPower_Required>();
            this.RS_Manual_Data_Collection = new HashSet<RS_Manual_Data_Collection>();
            this.RS_Model_Attribute_Master = new HashSet<RS_Model_Attribute_Master>();
            this.RS_MT_Calibration_Log = new HashSet<RS_MT_Calibration_Log>();
            this.RS_MT_Calibration = new HashSet<RS_MT_Calibration>();
            this.RS_MT_Machines = new HashSet<RS_MT_Machines>();
            this.RS_MT_Maintenance_Manual_Data = new HashSet<RS_MT_Maintenance_Manual_Data>();
            this.RS_MT_Preventive_Maintenance_Log_New = new HashSet<RS_MT_Preventive_Maintenance_Log_New>();
            this.RS_MT_Shop_Manual_Data_Collection = new HashSet<RS_MT_Shop_Manual_Data_Collection>();
            this.RS_MT_Ticket = new HashSet<RS_MT_Ticket>();
            this.RS_OM_Order_Plan_History = new HashSet<RS_OM_Order_Plan_History>();
            this.RS_OM_Order_Retrieval = new HashSet<RS_OM_Order_Retrieval>();
            this.RS_OM_Order_Status_Live = new HashSet<RS_OM_Order_Status_Live>();
            this.RS_OM_Order_Status_Log = new HashSet<RS_OM_Order_Status_Log>();
            this.RS_OM_Platform = new HashSet<RS_OM_Platform>();
            this.RS_On_Job_Training_Data = new HashSet<RS_On_Job_Training_Data>();
            this.RS_Partgroup = new HashSet<RS_Partgroup>();
            this.RS_Partgroup1 = new HashSet<RS_Partgroup>();
            this.RS_Partmaster = new HashSet<RS_Partmaster>();
            this.RS_Platform = new HashSet<RS_Platform>();
            this.RS_PM_Activity_Log = new HashSet<RS_PM_Activity_Log>();
            this.RS_PM_Activity_Part_Log = new HashSet<RS_PM_Activity_Part_Log>();
            this.RS_PM_Activity_Part = new HashSet<RS_PM_Activity_Part>();
            this.RS_PM_Activity = new HashSet<RS_PM_Activity>();
            this.RS_Route_Configurations = new HashSet<RS_Route_Configurations>();
            this.RS_Route_Marriage_Shop = new HashSet<RS_Route_Marriage_Shop>();
            this.RS_Route_Marriage_Shop1 = new HashSet<RS_Route_Marriage_Shop>();
            this.RS_Route_Marriage_Station = new HashSet<RS_Route_Marriage_Station>();
            this.RS_Route_Marriage_Station1 = new HashSet<RS_Route_Marriage_Station>();
            this.RS_Setup = new HashSet<RS_Setup>();
            this.RS_SOP = new HashSet<RS_SOP>();
            this.RS_Station_Setup_Mapping = new HashSet<RS_Station_Setup_Mapping>();
            this.RS_Station_Tracking = new HashSet<RS_Station_Tracking>();
            this.RS_Stations = new HashSet<RS_Stations>();
            this.RS_UserActivity_Log = new HashSet<RS_UserActivity_Log>();
        }
    
        public decimal Line_ID { get; set; }
        public string Line_Name { get; set; }
        public string Line_Description { get; set; }
        public Nullable<decimal> Plant_ID { get; set; }
        public decimal Shop_ID { get; set; }
        public Nullable<decimal> Line_Type_Id { get; set; }
        public Nullable<bool> Is_Conveyor { get; set; }
        public Nullable<System.TimeSpan> TACT_Time { get; set; }
        public Nullable<bool> Allow_NoScan_LineStop { get; set; }
        public Nullable<bool> Is_Shop_Line_Start { get; set; }
        public Nullable<bool> Is_Shop_Line_End { get; set; }
        public Nullable<decimal> Tact_Time_Sec { get; set; }
        public Nullable<bool> isLineStop { get; set; }
        public Nullable<System.DateTime> LineStart_Time { get; set; }
        public Nullable<System.DateTime> LineStop_Time { get; set; }
        public Nullable<decimal> LineStopStation_ID { get; set; }
        public Nullable<System.DateTime> LineMove_Time { get; set; }
        public Nullable<long> Current_Stoppage_Seconds { get; set; }
        public Nullable<bool> Is_Sub_Assembly { get; set; }
        public Nullable<bool> isPLC { get; set; }
        public string Line_Code { get; set; }
        public Nullable<bool> Is_Assign { get; set; }
        public Nullable<decimal> Line_Stop_Percentage { get; set; }
        public Nullable<bool> Is_StartOrder_BasedOn_TAKT { get; set; }
        public string SAP_Line_Code { get; set; }
        public bool Is_Transferred { get; set; }
        public bool Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public string Inserted_Host { get; set; }
        public decimal Inserted_User_ID { get; set; }
        public System.DateTime Inserted_Date { get; set; }
        public string Updated_Host { get; set; }
        public Nullable<decimal> Updated_User_ID { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<bool> Is_Buildsheet { get; set; }
        public Nullable<bool> Is_PRN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Abs_Operator_Transfer_Allocation> RS_Abs_Operator_Transfer_Allocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Abs_Operator_Transfer_Allocation> RS_Abs_Operator_Transfer_Allocation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_AM_Default_URL> RS_AM_Default_URL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_AM_Employee_SkillSet> RS_AM_Employee_SkillSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_AM_LeaveManagement> RS_AM_LeaveManagement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_AM_Line_Supervisor_Mapping> RS_AM_Line_Supervisor_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_AM_Operator_Change_Request> RS_AM_Operator_Change_Request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_AM_Operator_Station_Allocation> RS_AM_Operator_Station_Allocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_AM_Operator_Station_Allocation_History> RS_AM_Operator_Station_Allocation_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_AM_Operator_Station_Allocation_History> RS_AM_Operator_Station_Allocation_History1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_AM_Station_Operation> RS_AM_Station_Operation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Assign_OperatorToSupervisor> RS_Assign_OperatorToSupervisor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Ctrl_Alarm_Signals> RS_Ctrl_Alarm_Signals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Ctrl_Alarm_Signals_History> RS_Ctrl_Alarm_Signals_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Ctrl_Conveyor_Signal> RS_Ctrl_Conveyor_Signal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Ctrl_Cyl_Head_MB_CON_Data> RS_Ctrl_Cyl_Head_MB_CON_Data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Ctrl_Equipment_Status> RS_Ctrl_Equipment_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Ctrl_Equipment_Status_History> RS_Ctrl_Equipment_Status_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Ctrl_Leak_Testing> RS_Ctrl_Leak_Testing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Ctrl_Line_Stop_History> RS_Ctrl_Line_Stop_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Ctrl_LineStopEmergency> RS_Ctrl_LineStopEmergency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Ctrl_MBCAB_CONROD> RS_Ctrl_MBCAB_CONROD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Ctrl_Oil_Dispencing> RS_Ctrl_Oil_Dispencing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Ctrl_Station_Status> RS_Ctrl_Station_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Dashboard_Master> RS_Dashboard_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Department> RS_Department { get; set; }
        public virtual RS_Employee RS_Employee { get; set; }
        public virtual RS_Employee RS_Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Error_Log> RS_Error_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_External_Training_Data> RS_External_Training_Data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Help_Category> RS_Help_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Help_Desk> RS_Help_Desk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_History_Line_TACT_Time> RS_History_Line_TACT_Time { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_History_LineStop> RS_History_LineStop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_IoT_Tags> RS_IoT_Tags { get; set; }
        public virtual RS_Line_Types RS_Line_Types { get; set; }
        public virtual RS_Plants RS_Plants { get; set; }
        public virtual RS_Shops RS_Shops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Lock_Table> RS_Lock_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Maintenance_Machine_Part> RS_Maintenance_Machine_Part { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Manifest> RS_Manifest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_ManPower_Required> RS_ManPower_Required { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Manual_Data_Collection> RS_Manual_Data_Collection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Model_Attribute_Master> RS_Model_Attribute_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_MT_Calibration_Log> RS_MT_Calibration_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_MT_Calibration> RS_MT_Calibration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_MT_Machines> RS_MT_Machines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_MT_Maintenance_Manual_Data> RS_MT_Maintenance_Manual_Data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_MT_Preventive_Maintenance_Log_New> RS_MT_Preventive_Maintenance_Log_New { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_MT_Shop_Manual_Data_Collection> RS_MT_Shop_Manual_Data_Collection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_MT_Ticket> RS_MT_Ticket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_OM_Order_Plan_History> RS_OM_Order_Plan_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_OM_Order_Retrieval> RS_OM_Order_Retrieval { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_OM_Order_Status_Live> RS_OM_Order_Status_Live { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_OM_Order_Status_Log> RS_OM_Order_Status_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_OM_Platform> RS_OM_Platform { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_On_Job_Training_Data> RS_On_Job_Training_Data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Partgroup> RS_Partgroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Partgroup> RS_Partgroup1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Partmaster> RS_Partmaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Platform> RS_Platform { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_PM_Activity_Log> RS_PM_Activity_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_PM_Activity_Part_Log> RS_PM_Activity_Part_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_PM_Activity_Part> RS_PM_Activity_Part { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_PM_Activity> RS_PM_Activity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Route_Configurations> RS_Route_Configurations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Route_Marriage_Shop> RS_Route_Marriage_Shop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Route_Marriage_Shop> RS_Route_Marriage_Shop1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Route_Marriage_Station> RS_Route_Marriage_Station { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Route_Marriage_Station> RS_Route_Marriage_Station1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Setup> RS_Setup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_SOP> RS_SOP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Station_Setup_Mapping> RS_Station_Setup_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Station_Tracking> RS_Station_Tracking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Stations> RS_Stations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_UserActivity_Log> RS_UserActivity_Log { get; set; }
    }
}
