//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_Maintenance_Part
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RS_Maintenance_Part()
        {
            this.RS_Maintenance_Machine_Part = new HashSet<RS_Maintenance_Machine_Part>();
            this.RS_PM_Activity_Part_Log = new HashSet<RS_PM_Activity_Part_Log>();
            this.RS_PM_Activity_Part = new HashSet<RS_PM_Activity_Part>();
        }
    
        public decimal Maintenance_Part_ID { get; set; }
        public string Part_Name { get; set; }
        public string Part_Desscription { get; set; }
        public Nullable<int> Qty { get; set; }
        public decimal Plant_ID { get; set; }
        public bool Is_Transferred { get; set; }
        public bool Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public string Inserted_Host { get; set; }
        public decimal Inserted_User_ID { get; set; }
        public System.DateTime Inserted_Date { get; set; }
        public string Updated_Host { get; set; }
        public Nullable<decimal> Updated_User_ID { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Maintenance_Machine_Part> RS_Maintenance_Machine_Part { get; set; }
        public virtual RS_Plants RS_Plants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_PM_Activity_Part_Log> RS_PM_Activity_Part_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_PM_Activity_Part> RS_PM_Activity_Part { get; set; }
    }
}
