//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_Menu_Role
    {
        public long Menu_Role_ID { get; set; }
        public long Menu_ID { get; set; }
        public decimal Role_ID { get; set; }
        public Nullable<decimal> Sub_Menu_ID { get; set; }
        public Nullable<int> Sort_Order { get; set; }
        public string Inserted_Host { get; set; }
        public Nullable<decimal> Inserted_User_ID { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string Updated_Host { get; set; }
        public Nullable<decimal> Updated_User_ID { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public bool Is_Transfered { get; set; }
        public bool Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public Nullable<decimal> Plant_ID { get; set; }
        public Nullable<bool> Is_Qdms { get; set; }
    
        public virtual RS_Menus RS_Menus { get; set; }
        public virtual RS_Roles RS_Roles { get; set; }
        public virtual RS_Sub_Menus RS_Sub_Menus { get; set; }
    }
}
