//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_Model_Attribute_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RS_Model_Attribute_Master()
        {
            this.RS_BIW_Part_Master = new HashSet<RS_BIW_Part_Master>();
            this.RS_Manifest = new HashSet<RS_Manifest>();
            this.RS_Model_Master = new HashSet<RS_Model_Master>();
            this.RS_SOP = new HashSet<RS_SOP>();
        }
    
        public decimal Model_Attribute_ID { get; set; }
        public decimal Platform_ID { get; set; }
        public Nullable<decimal> Sub_Assembly_ID { get; set; }
        public Nullable<decimal> Shop_ID { get; set; }
        public Nullable<decimal> Line_ID { get; set; }
        public string Attribution { get; set; }
        public Nullable<decimal> Plant_ID { get; set; }
        public bool Is_Transferred { get; set; }
        public bool Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public string Inserted_Host { get; set; }
        public Nullable<decimal> Inserted_User_ID { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string Updated_Host { get; set; }
        public Nullable<decimal> Updated_User_ID { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_BIW_Part_Master> RS_BIW_Part_Master { get; set; }
        public virtual RS_Lines RS_Lines { get; set; }
        public virtual RS_Major_Sub_Assembly RS_Major_Sub_Assembly { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Manifest> RS_Manifest { get; set; }
        public virtual RS_OM_Platform RS_OM_Platform { get; set; }
        public virtual RS_Plants RS_Plants { get; set; }
        public virtual RS_Shops RS_Shops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Model_Master> RS_Model_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_SOP> RS_SOP { get; set; }
    }
}
