//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_MAST_SAP_USER
    {
        public string SYSTEM { get; set; }
        public string USERID { get; set; }
        public string PASSWORD { get; set; }
        public string IPMSUserID { get; set; }
        public string OSUserID { get; set; }
        public string OSHostname { get; set; }
        public System.DateTime LastDateTime { get; set; }
        public bool Active { get; set; }
        public bool Is_Transfered { get; set; }
        public bool Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public decimal SAP_ID { get; set; }
        public Nullable<decimal> Plant_ID { get; set; }
        public string Inserted_Host { get; set; }
        public Nullable<decimal> Inserted_User_ID { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public Nullable<decimal> Updated_User_ID { get; set; }
        public string Updated_Host { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
    
        public virtual RS_Plants RS_Plants { get; set; }
    }
}
