//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_MT_Calibration_Users
    {
        public decimal CU_ID { get; set; }
        public decimal Station_ID { get; set; }
        public decimal C_Tool_ID { get; set; }
        public decimal User_ID { get; set; }
        public bool Is_Transfered { get; set; }
        public bool Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
    
        public virtual RS_Employee RS_Employee { get; set; }
        public virtual RS_MT_Calibration RS_MT_Calibration { get; set; }
        public virtual RS_Stations RS_Stations { get; set; }
    }
}
