//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_Manifest
    {
        public decimal Manifest_ID { get; set; }
        public string Part_No { get; set; }
        public string Part_Description { get; set; }
        public string Identification { get; set; }
        public string Image_Name { get; set; }
        public decimal Plant_ID { get; set; }
        public decimal Shop_ID { get; set; }
        public decimal Line_ID { get; set; }
        public decimal Station_ID { get; set; }
        public Nullable<bool> Is_ParentModel_Manifest { get; set; }
        public Nullable<decimal> Platform_ID { get; set; }
        public Nullable<decimal> Model_Attribute_ID { get; set; }
        public Nullable<decimal> Attribute_ID { get; set; }
        public Nullable<long> Is_Deleted { get; set; }
        public Nullable<bool> Is_Transfered { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public Nullable<bool> Is_Purgeable { get; set; }
        public string Inserted_Host { get; set; }
        public decimal Inserted_User_ID { get; set; }
        public System.DateTime Inserted_Date { get; set; }
        public string Updated_Host { get; set; }
        public Nullable<decimal> Updated_User_ID { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
    
        public virtual RS_Attribution_Parameters RS_Attribution_Parameters { get; set; }
        public virtual RS_Employee RS_Employee { get; set; }
        public virtual RS_Employee RS_Employee1 { get; set; }
        public virtual RS_Lines RS_Lines { get; set; }
        public virtual RS_Model_Attribute_Master RS_Model_Attribute_Master { get; set; }
        public virtual RS_OM_Platform RS_OM_Platform { get; set; }
        public virtual RS_Plants RS_Plants { get; set; }
        public virtual RS_Shops RS_Shops { get; set; }
        public virtual RS_Stations RS_Stations { get; set; }
    }
}
