//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_MT_Preventive_Maintenance_Log_New
    {
        public decimal PM_Log_ID { get; set; }
        public decimal Plant_ID { get; set; }
        public decimal Station_ID { get; set; }
        public decimal Shop_ID { get; set; }
        public decimal Line_ID { get; set; }
        public decimal Machine_ID { get; set; }
        public Nullable<bool> Is_Acknowledge { get; set; }
        public System.DateTime Scheduled_Date { get; set; }
        public Nullable<System.DateTime> Last_Done_Date { get; set; }
        public Nullable<System.DateTime> Confirmed_Date { get; set; }
        public string Acknowledge_User_ID { get; set; }
        public Nullable<System.DateTime> Acknowledge_Date { get; set; }
        public string Confirmed_User_ID { get; set; }
        public Nullable<System.DateTime> Postpone_Date { get; set; }
        public string Postpone_Reason { get; set; }
        public string Postpone_User_ID { get; set; }
        public Nullable<bool> Is_Confirmed { get; set; }
        public Nullable<bool> Is_PostPoned { get; set; }
        public bool Is_Transferred { get; set; }
        public bool Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public string Inserted_Host { get; set; }
        public Nullable<decimal> Inserted_User_ID { get; set; }
        public System.DateTime Inserted_Date { get; set; }
        public string Updated_Host { get; set; }
        public Nullable<decimal> Updated_User_ID { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
    
        public virtual RS_Lines RS_Lines { get; set; }
        public virtual RS_MT_Machines RS_MT_Machines { get; set; }
        public virtual RS_Plants RS_Plants { get; set; }
        public virtual RS_Shops RS_Shops { get; set; }
        public virtual RS_Stations RS_Stations { get; set; }
    }
}
