//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_Notification_Modules
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RS_Notification_Modules()
        {
            this.RS_Notification_Config = new HashSet<RS_Notification_Config>();
        }
    
        public long Module_ID { get; set; }
        public string Module_Name { get; set; }
        public string Scheduler_Type { get; set; }
        public string Scheduler_Time { get; set; }
        public Nullable<int> Scheduler_Seconds { get; set; }
        public string Scheduled_Timings { get; set; }
        public Nullable<int> First_Escalation_Day { get; set; }
        public Nullable<int> Second_Escalation_Day { get; set; }
        public Nullable<int> Third_Escalation_Day { get; set; }
        public bool Is_Shift { get; set; }
        public bool Is_intervel { get; set; }
        public string intervel_Time { get; set; }
        public bool Is_Email { get; set; }
        public string next_Schedule_Time { get; set; }
        public string escalation_Time { get; set; }
        public string next_Escalation_Time { get; set; }
        public Nullable<decimal> Plant_ID { get; set; }
        public Nullable<decimal> Shop_ID { get; set; }
        public Nullable<decimal> Line_ID { get; set; }
        public Nullable<decimal> Station_ID { get; set; }
        public Nullable<decimal> Shift_ID { get; set; }
        public bool Is_Transferred { get; set; }
        public bool Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public string Inserted_Host { get; set; }
        public Nullable<decimal> Inserted_User_ID { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string Updated_Host { get; set; }
        public Nullable<decimal> Updated_User_ID { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
    
        public virtual RS_Employee RS_Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Notification_Config> RS_Notification_Config { get; set; }
    }
}
