//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_OM_BuildSheet_Print
    {
        public decimal RowID { get; set; }
        public string Serial_No { get; set; }
        public Nullable<decimal> Station_ID { get; set; }
        public byte[] PDF_Bytes { get; set; }
        public string PDF_FileName { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public Nullable<decimal> Inserted_User_ID { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
    }
}
