//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_OM_Order_Remarks
    {
        public long Row_ID { get; set; }
        public int Order_ID { get; set; }
        public string Remark_Category { get; set; }
        public string Remark_Msg { get; set; }
        public Nullable<decimal> Inserted_UserID { get; set; }
        public System.DateTime Inserted_Time { get; set; }
        public Nullable<bool> Is_Transfered { get; set; }
        public Nullable<bool> Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
    }
}
