//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_OM_ShopFloor_Holded_RSN
    {
        public long Row_ID { get; set; }
        public int Order_ID { get; set; }
        public int RSN { get; set; }
        public System.DateTime Inserted_Date { get; set; }
        public Nullable<bool> Is_Started { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public Nullable<bool> Is_Transfered { get; set; }
        public Nullable<bool> Is_Purgeable { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
    }
}
