//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_OM_Order_List
    {
        public decimal Order_ID { get; set; }
        public decimal Plant_ID { get; set; }
        public decimal Shop_ID { get; set; }
        public decimal Line_ID { get; set; }
        public decimal Station_ID { get; set; }
        public string Order_No { get; set; }
        public string Serial_No { get; set; }
        public string Model_Code { get; set; }
        public string partno { get; set; }
        public Nullable<decimal> Series_Code { get; set; }
        public Nullable<decimal> DSN { get; set; }
        public Nullable<decimal> PSN { get; set; }
        public System.DateTime Entry_Date { get; set; }
        public System.TimeSpan Entry_Time { get; set; }
        public Nullable<decimal> Partgroup_ID { get; set; }
        public Nullable<bool> Is_Transferred { get; set; }
        public Nullable<bool> Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public string Inserted_Host { get; set; }
        public decimal Inserted_User_ID { get; set; }
        public System.DateTime Inserted_Date { get; set; }
        public string Updated_Host { get; set; }
        public Nullable<decimal> Updated_User_ID { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public string Order_Status { get; set; }
        public string Param_1 { get; set; }
        public string Param_2 { get; set; }
        public string Param_3 { get; set; }
        public string Param_4 { get; set; }
        public string Param_5 { get; set; }
        public Nullable<bool> Is_Rejected { get; set; }
        public bool Is_Error_Proffing_Done { get; set; }
        public bool Is_Xylo_Error_Proffing_Done { get; set; }
        public Nullable<decimal> Started_Shift_ID { get; set; }
        public Nullable<bool> CRS_Body { get; set; }
        public Nullable<System.DateTime> CRS_Take_Out_Date { get; set; }
        public Nullable<System.DateTime> CRS_Take_In_Date { get; set; }
        public string Skid_Number { get; set; }
        public string SDP_Status { get; set; }
        public Nullable<bool> Is_Drona_To_VMS { get; set; }
        public Nullable<bool> Is_VMS_To_Drona { get; set; }
        public Nullable<System.DateTime> VMS_Punch_Time { get; set; }
        public Nullable<System.DateTime> ECA_Date { get; set; }
        public Nullable<System.DateTime> UB10_WorkComplete_Date { get; set; }
        public string VIN_Number { get; set; }
        public Nullable<bool> Is_Drona_To_IPMS_Paintshop { get; set; }
        public Nullable<bool> Is_Roof { get; set; }
        public Nullable<bool> Is_DataSendToMarkingMachine { get; set; }
        public Nullable<bool> Q_Status { get; set; }
    
        public virtual RS_Series RS_Series { get; set; }
    }
}
