//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_OM_VMS_Error_Log
    {
        public decimal Row_Id { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string Order_No { get; set; }
        public string Erro_Message { get; set; }
    }
}
