//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_OM_Planned_Orders
    {
        public long Row_ID { get; set; }
        public Nullable<decimal> Plant_ID { get; set; }
        public Nullable<decimal> Shop_ID { get; set; }
        public Nullable<int> Group_No { get; set; }
        public Nullable<int> Order_ID { get; set; }
        public string Order_No { get; set; }
        public string Order_Status { get; set; }
        public string Parent_Model_Code { get; set; }
        public Nullable<decimal> Parent_Series_Code { get; set; }
        public string Model_Code { get; set; }
        public Nullable<decimal> Series_Code { get; set; }
        public string Eng_Model_Code { get; set; }
        public string Eng_Series { get; set; }
        public string Trans_Model_Code { get; set; }
        public string Trans_Series { get; set; }
        public Nullable<decimal> RSN { get; set; }
        public Nullable<System.DateTime> Planned_Date { get; set; }
        public Nullable<System.DateTime> Inserted_Time { get; set; }
        public Nullable<System.DateTime> Last_Status_Change_Time { get; set; }
        public Nullable<bool> Is_Spill_Over { get; set; }
        public Nullable<bool> Is_Transfered { get; set; }
        public Nullable<bool> Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public string Planned_Time { get; set; }
        public Nullable<bool> Is_Rejected { get; set; }
    }
}
