//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_PM_Activity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RS_PM_Activity()
        {
            this.RS_PM_Activity_Log = new HashSet<RS_PM_Activity_Log>();
            this.RS_PM_Activity_Part = new HashSet<RS_PM_Activity_Part>();
        }
    
        public decimal Activity_ID { get; set; }
        public string Activity_Name { get; set; }
        public string Activity_Description { get; set; }
        public decimal Machine_ID { get; set; }
        public decimal Plant_ID { get; set; }
        public decimal Shop_ID { get; set; }
        public decimal Line_ID { get; set; }
        public decimal Station_ID { get; set; }
        public decimal Frequency { get; set; }
        public System.DateTime Start_Date { get; set; }
        public Nullable<System.DateTime> Last_Date { get; set; }
        public decimal Activity_Owner_ID { get; set; }
        public bool Is_Transferred { get; set; }
        public bool Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public string Inserted_Host { get; set; }
        public decimal Inserted_User_ID { get; set; }
        public System.DateTime Inserted_Date { get; set; }
        public string Updated_Host { get; set; }
        public Nullable<decimal> Updated_User_ID { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<bool> Is_Value_Based { get; set; }
        public Nullable<bool> Is_User_Value_Based { get; set; }
        public Nullable<double> Lower_Limit { get; set; }
        public Nullable<double> Upper_Limit { get; set; }
        public decimal EQP_ID { get; set; }
        public Nullable<System.DateTime> Next_Cycle_Date { get; set; }
        public Nullable<decimal> M_ID { get; set; }
    
        public virtual RS_Employee RS_Employee { get; set; }
        public virtual RS_Lines RS_Lines { get; set; }
        public virtual RS_MT_Machines RS_MT_Machines { get; set; }
        public virtual RS_MT_Unit_Of_Measurement RS_MT_Unit_Of_Measurement { get; set; }
        public virtual RS_Plants RS_Plants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_PM_Activity_Log> RS_PM_Activity_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_PM_Activity_Part> RS_PM_Activity_Part { get; set; }
        public virtual RS_PM_Equipment RS_PM_Equipment { get; set; }
        public virtual RS_Shops RS_Shops { get; set; }
        public virtual RS_Stations RS_Stations { get; set; }
    }
}
