//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_Partmaster
    {
        public decimal PartMaster_ID { get; set; }
        public decimal Plant_ID { get; set; }
        public decimal Shop_ID { get; set; }
        public Nullable<decimal> Line_ID { get; set; }
        public Nullable<decimal> Station_ID { get; set; }
        public Nullable<decimal> Partgroup_ID { get; set; }
        public string Part_No { get; set; }
        public string Part_Description { get; set; }
        public string Stage { get; set; }
        public Nullable<decimal> Series_Code { get; set; }
        public bool Genealogy { get; set; }
        public bool Error_Proofing { get; set; }
        public bool Kitting { get; set; }
        public bool Sequence { get; set; }
        public bool Traceability { get; set; }
        public bool SOB { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public Nullable<bool> Is_Transfered { get; set; }
        public Nullable<bool> Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public decimal Inserted_User_ID { get; set; }
        public System.DateTime Inserted_Date { get; set; }
        public decimal Updated_User_ID { get; set; }
        public System.DateTime Updated_Date { get; set; }
        public bool isFinished { get; set; }
        public bool is_Non_RS_Barcode { get; set; }
        public string Std_Char { get; set; }
        public Nullable<short> Start_Position { get; set; }
        public Nullable<short> Month_Start_Position { get; set; }
        public Nullable<short> Year_Start_Position { get; set; }
        public Nullable<int> Month_Identifier { get; set; }
        public Nullable<int> Year_Identifier { get; set; }
        public bool Is_Part_Create_Order { get; set; }
        public Nullable<decimal> PartID { get; set; }
    
        public virtual RS_Lines RS_Lines { get; set; }
        public virtual RS_Partgroup RS_Partgroup { get; set; }
        public virtual RS_Plants RS_Plants { get; set; }
        public virtual RS_Series RS_Series { get; set; }
        public virtual RS_Shops RS_Shops { get; set; }
        public virtual RS_Stations RS_Stations { get; set; }
    }
}
