//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_PrinterConfig
    {
        public decimal PC_ID { get; set; }
        public decimal Station_ID { get; set; }
        public Nullable<bool> Is_DefaultPrinter { get; set; }
        public Nullable<bool> Is_ExtraPrinter { get; set; }
        public string DefaultPrinterName { get; set; }
        public string ExtraPrinterName { get; set; }
        public string DefaultPRNFileName { get; set; }
        public string ExtraPRNFileName { get; set; }
        public Nullable<decimal> PrintQuantity { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
    
        public virtual RS_Stations RS_Stations { get; set; }
    }
}
