//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_PM_Activity_Log
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RS_PM_Activity_Log()
        {
            this.RS_PM_Activity_Part_Log = new HashSet<RS_PM_Activity_Part_Log>();
        }
    
        public decimal PM_Activity_Log_ID { get; set; }
        public decimal Activity_ID { get; set; }
        public decimal Machine_ID { get; set; }
        public decimal Plant_ID { get; set; }
        public decimal Shop_ID { get; set; }
        public decimal Line_ID { get; set; }
        public decimal Station_ID { get; set; }
        public System.DateTime Due_Date { get; set; }
        public Nullable<bool> Is_Confirmed { get; set; }
        public Nullable<decimal> Confirmed_User_ID { get; set; }
        public Nullable<System.DateTime> Confirmed_Date { get; set; }
        public Nullable<int> Escalation_Level { get; set; }
        public Nullable<System.DateTime> First_Escalation_Time { get; set; }
        public Nullable<System.DateTime> Second_escalation_Time { get; set; }
        public Nullable<System.DateTime> Third_Escalation_Time { get; set; }
        public bool Is_Transferred { get; set; }
        public bool Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public string Inserted_Host { get; set; }
        public Nullable<decimal> Inserted_User_ID { get; set; }
        public System.DateTime Inserted_Date { get; set; }
        public string Updated_Host { get; set; }
        public Nullable<decimal> Updated_User_ID { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public string Observation_Before_PM { get; set; }
        public string Observation_After_PM { get; set; }
    
        public virtual RS_Lines RS_Lines { get; set; }
        public virtual RS_MT_Machines RS_MT_Machines { get; set; }
        public virtual RS_Plants RS_Plants { get; set; }
        public virtual RS_PM_Activity RS_PM_Activity { get; set; }
        public virtual RS_Shops RS_Shops { get; set; }
        public virtual RS_Stations RS_Stations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_PM_Activity_Part_Log> RS_PM_Activity_Part_Log { get; set; }
    }
}
