//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_Qlty_PartWise
    {
        public decimal Row_Id { get; set; }
        public Nullable<decimal> Part_ID { get; set; }
        public string Part_Name { get; set; }
        public Nullable<decimal> Platform_ID { get; set; }
        public Nullable<decimal> Workstation_ID { get; set; }
        public decimal Plant_ID { get; set; }
        public decimal Shop_ID { get; set; }
        public Nullable<decimal> Line_ID { get; set; }
        public decimal BuyOffCode { get; set; }
        public decimal Stage_ID { get; set; }
        public Nullable<decimal> Defect_ID { get; set; }
        public Nullable<decimal> Location_ID { get; set; }
        public Nullable<decimal> Quality_Severity_ID { get; set; }
        public Nullable<bool> Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public string Inserted_Host { get; set; }
        public Nullable<decimal> Inserted_User_ID { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string Updated_Host { get; set; }
        public Nullable<decimal> Updated_User_ID { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<decimal> Attribute_ID { get; set; }
        public Nullable<int> REWORK_DURATION { get; set; }
    }
}
