//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_Qlty_Image_Part_Defect
    {
        public decimal GIP_ID { get; set; }
        public decimal Plant_ID { get; set; }
        public decimal Shop_ID { get; set; }
        public Nullable<decimal> Line_ID { get; set; }
        public Nullable<decimal> Stage_ID { get; set; }
        public decimal BuyoffCode { get; set; }
        public decimal Defect_ID { get; set; }
        public decimal Image_ID { get; set; }
        public decimal Image_Grid_ID { get; set; }
        public decimal Part_ID { get; set; }
        public Nullable<decimal> Platform_ID { get; set; }
        public Nullable<bool> Is_Transfered { get; set; }
        public Nullable<bool> Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public string Inserted_Host { get; set; }
        public decimal Inserted_User_ID { get; set; }
        public System.DateTime Inserted_Date { get; set; }
        public string Updated_Host { get; set; }
        public Nullable<decimal> Updated_User_ID { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
    
        public virtual RS_Employee RS_Employee { get; set; }
        public virtual RS_Plants RS_Plants { get; set; }
        public virtual RS_Qlty_Image RS_Qlty_Image { get; set; }
        public virtual RS_Qlty_Image_Grid RS_Qlty_Image_Grid { get; set; }
        public virtual RS_Qlty_Image_Part_Defect RS_Qlty_Image_Part_Defect1 { get; set; }
        public virtual RS_Qlty_Image_Part_Defect RS_Qlty_Image_Part_Defect2 { get; set; }
        public virtual RS_Qlty_Mstr_Stage RS_Qlty_Mstr_Stage { get; set; }
        public virtual RS_Qlty_Part RS_Qlty_Part { get; set; }
        public virtual RS_Shops RS_Shops { get; set; }
    }
}
