//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_Quality_Station_List
    {
        public decimal QS_ID { get; set; }
        public decimal Plant_ID { get; set; }
        public decimal Shop_ID { get; set; }
        public decimal Line_ID { get; set; }
        public decimal Station_ID { get; set; }
        public Nullable<bool> Is_Take_In_Take_Out { get; set; }
        public Nullable<bool> Is_Production_Book { get; set; }
        public Nullable<bool> Is_Final_Station { get; set; }
        public Nullable<bool> Is_Rework { get; set; }
        public Nullable<bool> Is_Process_Audit { get; set; }
        public Nullable<bool> Is_Gate_Audit { get; set; }
        public Nullable<bool> Is_Tablet { get; set; }
        public Nullable<bool> Is_Part_Base { get; set; }
        public Nullable<bool> Is_CheckList_Base { get; set; }
        public Nullable<int> Is_Part_Base_Priority { get; set; }
        public Nullable<int> Is_CheckList_Base_Priority { get; set; }
        public Nullable<int> Is_Tablet_Priority { get; set; }
        public Nullable<bool> Is_PDI { get; set; }
        public Nullable<bool> Is_CT { get; set; }
        public Nullable<bool> Is_Roadtest { get; set; }
        public Nullable<bool> Is_Transferred { get; set; }
        public Nullable<bool> Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public Nullable<bool> Is_Domestic { get; set; }
        public Nullable<bool> Is_Export { get; set; }
        public string Inserted_Host { get; set; }
        public decimal Inserted_User_ID { get; set; }
        public System.DateTime Inserted_Date { get; set; }
        public string Updated_Host { get; set; }
        public Nullable<decimal> Updated_User_ID { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<bool> Is_Equipment_Create { get; set; }
    }
}
