//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_Quality_Defect
    {
        public decimal Defect_ID { get; set; }
        public string Defect_Name { get; set; }
        public string Defect_Description { get; set; }
        public decimal Plant_ID { get; set; }
        public Nullable<decimal> Shop_ID { get; set; }
        public Nullable<decimal> Checkpoint_ID { get; set; }
        public Nullable<decimal> Defect_Origin_Shop_ID { get; set; }
        public Nullable<bool> Is_Transfered { get; set; }
        public Nullable<decimal> Defect_Category_ID { get; set; }
        public Nullable<bool> Is_Critical_Defect { get; set; }
        public Nullable<bool> Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public string Inserted_Host { get; set; }
        public decimal Inserted_User_ID { get; set; }
        public System.DateTime Inserted_Date { get; set; }
        public string Updated_Host { get; set; }
        public Nullable<decimal> Updated_User_ID { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
    }
}
