//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_Status
    {
        public decimal Row_ID { get; set; }
        public string Status { get; set; }
        public Nullable<int> Sort_Order { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<decimal> Shop_ID { get; set; }
        public Nullable<int> Group_Id { get; set; }
    }
}
