//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_Setup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RS_Setup()
        {
            this.RS_AM_Operator_Station_Allocation = new HashSet<RS_AM_Operator_Station_Allocation>();
            this.RS_AM_Operator_Station_Allocation_History = new HashSet<RS_AM_Operator_Station_Allocation_History>();
            this.RS_Dashboard_Master = new HashSet<RS_Dashboard_Master>();
            this.RS_External_Training_Data = new HashSet<RS_External_Training_Data>();
            this.RS_ManPower_Required = new HashSet<RS_ManPower_Required>();
            this.RS_On_Job_Training_Data = new HashSet<RS_On_Job_Training_Data>();
            this.RS_Station_Setup_Mapping = new HashSet<RS_Station_Setup_Mapping>();
        }
    
        public decimal Setup_ID { get; set; }
        public string Setup_Name { get; set; }
        public string Setup_Description { get; set; }
        public Nullable<int> No_Of_Stations { get; set; }
        public Nullable<decimal> Plant_ID { get; set; }
        public Nullable<decimal> Shop_ID { get; set; }
        public Nullable<decimal> Line_ID { get; set; }
        public Nullable<bool> Is_Transferred { get; set; }
        public Nullable<bool> Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public string Inserted_Host { get; set; }
        public Nullable<decimal> Inserted_User_ID { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string Updated_Host { get; set; }
        public Nullable<decimal> Updated_User_ID { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_AM_Operator_Station_Allocation> RS_AM_Operator_Station_Allocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_AM_Operator_Station_Allocation_History> RS_AM_Operator_Station_Allocation_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Dashboard_Master> RS_Dashboard_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_External_Training_Data> RS_External_Training_Data { get; set; }
        public virtual RS_Lines RS_Lines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_ManPower_Required> RS_ManPower_Required { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_On_Job_Training_Data> RS_On_Job_Training_Data { get; set; }
        public virtual RS_Plants RS_Plants { get; set; }
        public virtual RS_Shops RS_Shops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Station_Setup_Mapping> RS_Station_Setup_Mapping { get; set; }
    }
}
