//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_Shift
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RS_Shift()
        {
            this.RS_Abs_Operator_Transfer_Allocation = new HashSet<RS_Abs_Operator_Transfer_Allocation>();
            this.RS_AM_Operator_Change_Request = new HashSet<RS_AM_Operator_Change_Request>();
            this.RS_AM_Operator_Change_Request1 = new HashSet<RS_AM_Operator_Change_Request>();
            this.RS_AM_Operator_Station_Allocation = new HashSet<RS_AM_Operator_Station_Allocation>();
            this.RS_AM_Operator_Station_Allocation_History = new HashSet<RS_AM_Operator_Station_Allocation_History>();
            this.RS_Ctrl_Alarm_Signals_History = new HashSet<RS_Ctrl_Alarm_Signals_History>();
            this.RS_Ctrl_Line_Stop_History = new HashSet<RS_Ctrl_Line_Stop_History>();
            this.RS_Dashboard_Master = new HashSet<RS_Dashboard_Master>();
            this.RS_External_Training_Data = new HashSet<RS_External_Training_Data>();
            this.RS_History_LineStop = new HashSet<RS_History_LineStop>();
            this.RS_Machine_Shift_Data = new HashSet<RS_Machine_Shift_Data>();
            this.RS_Manual_Data_Collection = new HashSet<RS_Manual_Data_Collection>();
            this.RS_MT_Shop_Manual_Data_Collection = new HashSet<RS_MT_Shop_Manual_Data_Collection>();
            this.RS_On_Job_Training_Data = new HashSet<RS_On_Job_Training_Data>();
            this.RS_User_Attendance_Sheet = new HashSet<RS_User_Attendance_Sheet>();
        }
    
        public decimal Shift_ID { get; set; }
        public string Shift_Name { get; set; }
        public decimal Plant_ID { get; set; }
        public decimal Shop_ID { get; set; }
        public System.TimeSpan Shift_Start_Time { get; set; }
        public System.TimeSpan Shift_End_Time { get; set; }
        public Nullable<System.TimeSpan> Break1_Time { get; set; }
        public Nullable<System.TimeSpan> Break1_End_Time { get; set; }
        public Nullable<System.TimeSpan> Break2_Time { get; set; }
        public Nullable<System.TimeSpan> Break2_End_Time { get; set; }
        public Nullable<System.TimeSpan> Lunch_Time { get; set; }
        public Nullable<System.TimeSpan> Lunch_End_Time { get; set; }
        public Nullable<bool> Is_Transfered { get; set; }
        public Nullable<bool> Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public string Inserted_Host { get; set; }
        public decimal Inserted_User_ID { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string Updated_Host { get; set; }
        public Nullable<decimal> Updated_User_ID { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<System.TimeSpan> End_Time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Abs_Operator_Transfer_Allocation> RS_Abs_Operator_Transfer_Allocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_AM_Operator_Change_Request> RS_AM_Operator_Change_Request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_AM_Operator_Change_Request> RS_AM_Operator_Change_Request1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_AM_Operator_Station_Allocation> RS_AM_Operator_Station_Allocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_AM_Operator_Station_Allocation_History> RS_AM_Operator_Station_Allocation_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Ctrl_Alarm_Signals_History> RS_Ctrl_Alarm_Signals_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Ctrl_Line_Stop_History> RS_Ctrl_Line_Stop_History { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Dashboard_Master> RS_Dashboard_Master { get; set; }
        public virtual RS_Employee RS_Employee { get; set; }
        public virtual RS_Employee RS_Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_External_Training_Data> RS_External_Training_Data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_History_LineStop> RS_History_LineStop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Machine_Shift_Data> RS_Machine_Shift_Data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_Manual_Data_Collection> RS_Manual_Data_Collection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_MT_Shop_Manual_Data_Collection> RS_MT_Shop_Manual_Data_Collection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_On_Job_Training_Data> RS_On_Job_Training_Data { get; set; }
        public virtual RS_Plants RS_Plants { get; set; }
        public virtual RS_Shops RS_Shops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RS_User_Attendance_Sheet> RS_User_Attendance_Sheet { get; set; }
    }
}
