//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_Traceability
    {
        public decimal Trace_ID { get; set; }
        public Nullable<decimal> Plant_ID { get; set; }
        public Nullable<decimal> Shop_ID { get; set; }
        public Nullable<decimal> Station_ID { get; set; }
        public Nullable<bool> IsLineMode { get; set; }
        public Nullable<bool> IsReworkMode { get; set; }
        public string EngineSrNo { get; set; }
        public string ModelCode { get; set; }
        public string VINNumber { get; set; }
        public Nullable<System.DateTime> TDATE { get; set; }
        public string TTIME { get; set; }
        public string PARTID { get; set; }
        public string BOMPARTNO { get; set; }
        public string PartNo { get; set; }
        public string VCODE { get; set; }
        public Nullable<System.DateTime> MFGDATE { get; set; }
        public string MFGSHIFT { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public string ScanValue { get; set; }
        public string Inserted_Host { get; set; }
        public Nullable<decimal> Inserted_User_ID { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
    }
}
