//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_User_Plant_Concern
    {
        public int User_Concern_Id { get; set; }
        public Nullable<int> Sr_No { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<System.DateTime> Date_Of_Incidence { get; set; }
        public string Nature_Of_Concern { get; set; }
        public string Concern_Owner { get; set; }
        public string Engine_No { get; set; }
        public string Part_No { get; set; }
        public string Model { get; set; }
        public Nullable<int> Severity_ID { get; set; }
        public string Source_Detection { get; set; }
        public Nullable<int> Incidences { get; set; }
        public Nullable<int> Attribute_ID { get; set; }
        public string Attribute_6M { get; set; }
        public string Repeatation { get; set; }
        public string Detectable { get; set; }
        public Nullable<System.DateTime> Assembly_date { get; set; }
        public Nullable<int> Assembly_shift { get; set; }
        public Nullable<System.DateTime> Testing_Date { get; set; }
        public Nullable<int> Testing_Shift_Id { get; set; }
        public string Assembly_Associate { get; set; }
        public string Testing_Associate { get; set; }
        public string PDI_Associate { get; set; }
        public string Buyoff_Associate { get; set; }
        public string Associate_Type { get; set; }
        public string Root_Cause { get; set; }
        public string ICA { get; set; }
        public string PCA { get; set; }
        public string Resp { get; set; }
        public Nullable<System.DateTime> Target_Date { get; set; }
        public string Status { get; set; }
        public string Reversible { get; set; }
        public string FMEA_Ranking { get; set; }
        public string Engine_Replacement { get; set; }
        public Nullable<int> No_Of_Open_Days { get; set; }
        public string Testing_Type { get; set; }
        public Nullable<int> Shift_Id { get; set; }
        public Nullable<decimal> Plant_ID { get; set; }
        public Nullable<decimal> Shop_ID { get; set; }
        public Nullable<decimal> Line_ID { get; set; }
        public Nullable<bool> Is_Purgeable { get; set; }
        public Nullable<bool> Is_Edited { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public string Inserted_Host { get; set; }
        public Nullable<decimal> Inserted_User_ID { get; set; }
        public Nullable<System.DateTime> Inserted_Date { get; set; }
        public string Updated_Host { get; set; }
        public Nullable<decimal> Updated_User_ID { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<int> PDI_Buyoff { get; set; }
    }
}
