//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMachineAlarmType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMachineAlarmType() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("REIN_MES_System.App_LocalResources.ResourceMachineAlarmType", typeof(ResourceMachineAlarmType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Alarm Type.
        /// </summary>
        public static string Machine_Alarm_Type {
            get {
                return ResourceManager.GetString("Machine_Alarm_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm type is already exists. Please try with other name.
        /// </summary>
        public static string Machine_Alarm_Type_Error_Alarm_Type_Name_Exists {
            get {
                return ResourceManager.GetString("Machine_Alarm_Type_Error_Alarm_Type_Name_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select alarm type.
        /// </summary>
        public static string Machine_Alarm_Type_Error_Name_Select {
            get {
                return ResourceManager.GetString("Machine_Alarm_Type_Error_Name_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fault Background Color.
        /// </summary>
        public static string Machine_Alarm_Type_Label_Fault_Background_Color {
            get {
                return ResourceManager.GetString("Machine_Alarm_Type_Label_Fault_Background_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fault Forground Color.
        /// </summary>
        public static string Machine_Alarm_Type_Label_Fault_Forground_Color {
            get {
                return ResourceManager.GetString("Machine_Alarm_Type_Label_Fault_Forground_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healthy Background Color.
        /// </summary>
        public static string Machine_Alarm_Type_Label_Healthy_Background_Color {
            get {
                return ResourceManager.GetString("Machine_Alarm_Type_Label_Healthy_Background_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healthy Forground Color.
        /// </summary>
        public static string Machine_Alarm_Type_Label_Healthy_Forground_Color {
            get {
                return ResourceManager.GetString("Machine_Alarm_Type_Label_Healthy_Forground_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Alarm Type.
        /// </summary>
        public static string Machine_Alarm_Type_Label_Select {
            get {
                return ResourceManager.GetString("Machine_Alarm_Type_Label_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Type.
        /// </summary>
        public static string Machine_Alarm_Type_Label_Type {
            get {
                return ResourceManager.GetString("Machine_Alarm_Type_Label_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm type is added successfully.
        /// </summary>
        public static string Machine_Alarm_Type_Success_Add_Success {
            get {
                return ResourceManager.GetString("Machine_Alarm_Type_Success_Add_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm type is deleted successfully.
        /// </summary>
        public static string Machine_Alarm_Type_Success_Delete_Success {
            get {
                return ResourceManager.GetString("Machine_Alarm_Type_Success_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm type is edited successfully.
        /// </summary>
        public static string Machine_Alarm_Type_Success_Edit_Success {
            get {
                return ResourceManager.GetString("Machine_Alarm_Type_Success_Edit_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Alarm Type Form.
        /// </summary>
        public static string Machine_Alarm_Type_Title_Add_Alarm_Type {
            get {
                return ResourceManager.GetString("Machine_Alarm_Type_Title_Add_Alarm_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Type Detail.
        /// </summary>
        public static string Machine_Alarm_Type_Title_Alarm_Type_Detail {
            get {
                return ResourceManager.GetString("Machine_Alarm_Type_Title_Alarm_Type_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Alarm Type Form.
        /// </summary>
        public static string Machine_Alarm_Type_Title_Delete_Alarm_Type {
            get {
                return ResourceManager.GetString("Machine_Alarm_Type_Title_Delete_Alarm_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Alarm Type Form.
        /// </summary>
        public static string Machine_Alarm_Type_Title_Edit_Alarm_Type {
            get {
                return ResourceManager.GetString("Machine_Alarm_Type_Title_Edit_Alarm_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Type Lists.
        /// </summary>
        public static string Machine_Alarm_Type_Title_Lists {
            get {
                return ResourceManager.GetString("Machine_Alarm_Type_Title_Lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Checkpoint.
        /// </summary>
        public static string Quality_Checkpoint_Label_Selected {
            get {
                return ResourceManager.GetString("Quality_Checkpoint_Label_Selected", resourceCulture);
            }
        }
    }
}
