//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceRouteConfiguration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceRouteConfiguration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("REIN_MES_System.App_LocalResources.ResourceRouteConfiguration", typeof(ResourceRouteConfiguration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route Configuration.
        /// </summary>
        public static string Route_Configuration {
            get {
                return ResourceManager.GetString("Route_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route configuration is added successfully.
        /// </summary>
        public static string Route_Configuration_Success_Add_Success {
            get {
                return ResourceManager.GetString("Route_Configuration_Success_Add_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route Marriage Configure Form.
        /// </summary>
        public static string Route_Configuration_Title_Configure_Marriage_Route {
            get {
                return ResourceManager.GetString("Route_Configuration_Title_Configure_Marriage_Route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Route Form.
        /// </summary>
        public static string Route_Configuration_Title_Configure_Route {
            get {
                return ResourceManager.GetString("Route_Configuration_Title_Configure_Route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route Shop Marriage Form.
        /// </summary>
        public static string Route_Configuration_Title_Route_Shop_Marriage_Form {
            get {
                return ResourceManager.GetString("Route_Configuration_Title_Route_Shop_Marriage_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route Marriage.
        /// </summary>
        public static string Route_Marriage_Configuration {
            get {
                return ResourceManager.GetString("Route_Marriage_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route marriage configuration is already added.
        /// </summary>
        public static string Route_Marriage_Configuration_Error_Marriage_Exists {
            get {
                return ResourceManager.GetString("Route_Marriage_Configuration_Error_Marriage_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select marriage line.
        /// </summary>
        public static string Route_Marriage_Configuration_Error_Marriage_Line_Required {
            get {
                return ResourceManager.GetString("Route_Marriage_Configuration_Error_Marriage_Line_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select marriage line station.
        /// </summary>
        public static string Route_Marriage_Configuration_Error_Marriage_Line_Station_Required {
            get {
                return ResourceManager.GetString("Route_Marriage_Configuration_Error_Marriage_Line_Station_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select marriage shop.
        /// </summary>
        public static string Route_Marriage_Configuration_Error_Marriage_Shop_Required {
            get {
                return ResourceManager.GetString("Route_Marriage_Configuration_Error_Marriage_Shop_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select sub line.
        /// </summary>
        public static string Route_Marriage_Configuration_Error_Sub_Line_Required {
            get {
                return ResourceManager.GetString("Route_Marriage_Configuration_Error_Sub_Line_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select sub line station.
        /// </summary>
        public static string Route_Marriage_Configuration_Error_Sub_Line_Station_Required {
            get {
                return ResourceManager.GetString("Route_Marriage_Configuration_Error_Sub_Line_Station_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select sub shop.
        /// </summary>
        public static string Route_Marriage_Configuration_Error_Sub_Shop_Required {
            get {
                return ResourceManager.GetString("Route_Marriage_Configuration_Error_Sub_Shop_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marriage Line.
        /// </summary>
        public static string Route_Marriage_Configuration_Label_Marriage_Line {
            get {
                return ResourceManager.GetString("Route_Marriage_Configuration_Label_Marriage_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marriage Line Station.
        /// </summary>
        public static string Route_Marriage_Configuration_Label_Marriage_Line_Station {
            get {
                return ResourceManager.GetString("Route_Marriage_Configuration_Label_Marriage_Line_Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marriage Shop.
        /// </summary>
        public static string Route_Marriage_Configuration_Label_Marriage_Shop {
            get {
                return ResourceManager.GetString("Route_Marriage_Configuration_Label_Marriage_Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Line.
        /// </summary>
        public static string Route_Marriage_Configuration_Label_Sub_Line {
            get {
                return ResourceManager.GetString("Route_Marriage_Configuration_Label_Sub_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Line Station.
        /// </summary>
        public static string Route_Marriage_Configuration_Label_Sub_Line_Station {
            get {
                return ResourceManager.GetString("Route_Marriage_Configuration_Label_Sub_Line_Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Shop.
        /// </summary>
        public static string Route_Marriage_Configuration_Label_Sub_Shop {
            get {
                return ResourceManager.GetString("Route_Marriage_Configuration_Label_Sub_Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route marriage configuration is added successfully.
        /// </summary>
        public static string Route_Marriage_Configuration_Success_Add_Success {
            get {
                return ResourceManager.GetString("Route_Marriage_Configuration_Success_Add_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route marriage configuration is deleted successfully.
        /// </summary>
        public static string Route_Marriage_Configuration_Success_Delete_Success {
            get {
                return ResourceManager.GetString("Route_Marriage_Configuration_Success_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route Shop Marriage.
        /// </summary>
        public static string Route_Shop_Marriage_Configuration {
            get {
                return ResourceManager.GetString("Route_Shop_Marriage_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route shop marriage configuration is already added.
        /// </summary>
        public static string Route_Shop_Marriage_Configuration_Error_Marriage_Exists {
            get {
                return ResourceManager.GetString("Route_Shop_Marriage_Configuration_Error_Marriage_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route shop marriage configuration is added successfully.
        /// </summary>
        public static string Route_Shop_Marriage_Configuration_Success_Add_Success {
            get {
                return ResourceManager.GetString("Route_Shop_Marriage_Configuration_Success_Add_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route shop marriage configuration is deleted successfully.
        /// </summary>
        public static string Route_Shop_Marriage_Configuration_Success_Delete_Success {
            get {
                return ResourceManager.GetString("Route_Shop_Marriage_Configuration_Success_Delete_Success", resourceCulture);
            }
        }
    }
}
