//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceOperatorToSupervisor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceOperatorToSupervisor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("REIN_MES_System.App_LocalResources.ResourceOperatorToSupervisor", typeof(ResourceOperatorToSupervisor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Member To Officer.
        /// </summary>
        public static string OperatorToSupervisor {
            get {
                return ResourceManager.GetString("OperatorToSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the CellMemberToOfficer code.
        /// </summary>
        public static string OperatorToSupervisor_Error_OperatorToSupervisor_Code_Required {
            get {
                return ResourceManager.GetString("OperatorToSupervisor_Error_OperatorToSupervisor_Code_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CellMemberToOfficer name is already exists. Please try with other name.
        /// </summary>
        public static string OperatorToSupervisor_Error_OperatorToSupervisor_Name_Exists {
            get {
                return ResourceManager.GetString("OperatorToSupervisor_Error_OperatorToSupervisor_Name_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the CellMemberToOfficer name.
        /// </summary>
        public static string OperatorToSupervisor_Error_OperatorToSupervisor_Name_Required {
            get {
                return ResourceManager.GetString("OperatorToSupervisor_Error_OperatorToSupervisor_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CellMemberToOfficer Address.
        /// </summary>
        public static string OperatorToSupervisor_Label_OperatorToSupervisor_Address {
            get {
                return ResourceManager.GetString("OperatorToSupervisor_Label_OperatorToSupervisor_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string OperatorToSupervisor_Label_OperatorToSupervisor_City {
            get {
                return ResourceManager.GetString("OperatorToSupervisor_Label_OperatorToSupervisor_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CellMemberToOfficer Code.
        /// </summary>
        public static string OperatorToSupervisor_Label_OperatorToSupervisor_Code {
            get {
                return ResourceManager.GetString("OperatorToSupervisor_Label_OperatorToSupervisor_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string OperatorToSupervisor_Label_OperatorToSupervisor_Country {
            get {
                return ResourceManager.GetString("OperatorToSupervisor_Label_OperatorToSupervisor_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CellMemberToOfficer Name.
        /// </summary>
        public static string OperatorToSupervisor_Label_OperatorToSupervisor_Name {
            get {
                return ResourceManager.GetString("OperatorToSupervisor_Label_OperatorToSupervisor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string OperatorToSupervisor_Label_OperatorToSupervisor_State {
            get {
                return ResourceManager.GetString("OperatorToSupervisor_Label_OperatorToSupervisor_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CellMemberToOfficer is added successfully.
        /// </summary>
        public static string OperatorToSupervisor_Success_OperatorToSupervisor_Add_Success {
            get {
                return ResourceManager.GetString("OperatorToSupervisor_Success_OperatorToSupervisor_Add_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CellMemberToOfficer is deleted successfully.
        /// </summary>
        public static string OperatorToSupervisor_Success_OperatorToSupervisor_Delete_Success {
            get {
                return ResourceManager.GetString("OperatorToSupervisor_Success_OperatorToSupervisor_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CellMemberToOfficer is edited successfully.
        /// </summary>
        public static string OperatorToSupervisor_Success_OperatorToSupervisor_Edit_Success {
            get {
                return ResourceManager.GetString("OperatorToSupervisor_Success_OperatorToSupervisor_Edit_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add CellMemberToOfficer Form.
        /// </summary>
        public static string OperatorToSupervisor_Title_Add_OperatorToSupervisor {
            get {
                return ResourceManager.GetString("OperatorToSupervisor_Title_Add_OperatorToSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Cell Member To Officer Form.
        /// </summary>
        public static string OperatorToSupervisor_Title_Delete_OperatorToSupervisor {
            get {
                return ResourceManager.GetString("OperatorToSupervisor_Title_Delete_OperatorToSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Cell Member To Officer Form.
        /// </summary>
        public static string OperatorToSupervisor_Title_Edit_OperatorToSupervisor {
            get {
                return ResourceManager.GetString("OperatorToSupervisor_Title_Edit_OperatorToSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Member To Officer Detail.
        /// </summary>
        public static string OperatorToSupervisor_Title_OperatorToSupervisor_Detail {
            get {
                return ResourceManager.GetString("OperatorToSupervisor_Title_OperatorToSupervisor_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Member To Officer Lists.
        /// </summary>
        public static string OperatorToSupervisor_Title_OperatorToSupervisor_Lists {
            get {
                return ResourceManager.GetString("OperatorToSupervisor_Title_OperatorToSupervisor_Lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Site_Variable_Add {
            get {
                return ResourceManager.GetString("Site_Variable_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Site_Variable_Create {
            get {
                return ResourceManager.GetString("Site_Variable_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Site_Variable_Index {
            get {
                return ResourceManager.GetString("Site_Variable_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists.
        /// </summary>
        public static string Site_Variable_Lists {
            get {
                return ResourceManager.GetString("Site_Variable_Lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Member To Officer.
        /// </summary>
        public static string Site_Variable_OperatorToSupervisor {
            get {
                return ResourceManager.GetString("Site_Variable_OperatorToSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor Name is Required.
        /// </summary>
        public static string Supervisor_Error_Supervisor_Name_Required {
            get {
                return ResourceManager.GetString("Supervisor_Error_Supervisor_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor Name.
        /// </summary>
        public static string Supervisor_Label_Supervisor_Name {
            get {
                return ResourceManager.GetString("Supervisor_Label_Supervisor_Name", resourceCulture);
            }
        }
    }
}
