//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceShopwiseManualProduction {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceShopwiseManualProduction() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("REIN_MES_System.App_LocalResources.ResourceShopwiseManualProduction", typeof(ResourceShopwiseManualProduction).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manaul Shopwsie Production Added susscessfully .
        /// </summary>
        public static string Added_Manaul_Production {
            get {
                return ResourceManager.GetString("Added_Manaul_Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manaul Shopwsie Production Deleted susscessfully.
        /// </summary>
        public static string Delete_Manaul_Production {
            get {
                return ResourceManager.GetString("Delete_Manaul_Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopwise  manual Production is already exists  so do not added manual data.
        /// </summary>
        public static string Duplicate_Entry {
            get {
                return ResourceManager.GetString("Duplicate_Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manaul Shopwsie Production Edited susscessfully.
        /// </summary>
        public static string Edit_Manaul_Production {
            get {
                return ResourceManager.GetString("Edit_Manaul_Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopwise Manual Production.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop is already exists for this Shopwise Manual Production Please try with other shop.
        /// </summary>
        public static string Shop_Error_Production {
            get {
                return ResourceManager.GetString("Shop_Error_Production", resourceCulture);
            }
        }
    }
}
