//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMachineMaintenance {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMachineMaintenance() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("REIN_MES_System.App_LocalResources.ResourceMachineMaintenance", typeof(ResourceMachineMaintenance).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle (No of Months).
        /// </summary>
        public static string Cycle {
            get {
                return ResourceManager.GetString("Cycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is Required.
        /// </summary>
        public static string Email_Required {
            get {
                return ResourceManager.GetString("Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not Valid.
        /// </summary>
        public static string Email_Valid {
            get {
                return ResourceManager.GetString("Email_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle should in the range of 1 to 12 months.
        /// </summary>
        public static string Error_Cycle_Limit {
            get {
                return ResourceManager.GetString("Error_Cycle_Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency should in the range of 1 to 12 months.
        /// </summary>
        public static string Error_Frequency_Limit {
            get {
                return ResourceManager.GetString("Error_Frequency_Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Line.
        /// </summary>
        public static string Error_Line_Required {
            get {
                return ResourceManager.GetString("Error_Line_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Machine.
        /// </summary>
        public static string Error_Machine_Required {
            get {
                return ResourceManager.GetString("Error_Machine_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Plant.
        /// </summary>
        public static string Error_Plant_Required {
            get {
                return ResourceManager.GetString("Error_Plant_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Shop.
        /// </summary>
        public static string Error_Shop_Required {
            get {
                return ResourceManager.GetString("Error_Shop_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        public static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine.
        /// </summary>
        public static string Machine {
            get {
                return ResourceManager.GetString("Machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preventive Machine Maintenance.
        /// </summary>
        public static string Machine_Maintenance {
            get {
                return ResourceManager.GetString("Machine_Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine code is required.
        /// </summary>
        public static string Machine_Maintenance_Error_Equipment_Code_Required {
            get {
                return ResourceManager.GetString("Machine_Maintenance_Error_Equipment_Code_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Name already Exists.
        /// </summary>
        public static string Machine_Maintenance_Error_Equipment_Name_Exists {
            get {
                return ResourceManager.GetString("Machine_Maintenance_Error_Equipment_Name_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Name is Required.
        /// </summary>
        public static string Machine_Maintenance_Error_Equipment_Name_Required {
            get {
                return ResourceManager.GetString("Machine_Maintenance_Error_Equipment_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine added successfully.
        /// </summary>
        public static string Machine_Maintenance_Success_Machine_Maintenance_Add_Success {
            get {
                return ResourceManager.GetString("Machine_Maintenance_Success_Machine_Maintenance_Add_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine is deleted successfully.
        /// </summary>
        public static string Machine_Maintenance_Success_Machine_Maintenance_Delete_Success {
            get {
                return ResourceManager.GetString("Machine_Maintenance_Success_Machine_Maintenance_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine is edited successfully.
        /// </summary>
        public static string Machine_Maintenance_Success_Machine_Maintenance_Edit_Success {
            get {
                return ResourceManager.GetString("Machine_Maintenance_Success_Machine_Maintenance_Edit_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Machine Form.
        /// </summary>
        public static string Machine_Maintenance_Title_Add_Machine_Maintenance {
            get {
                return ResourceManager.GetString("Machine_Maintenance_Title_Add_Machine_Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Machine Form.
        /// </summary>
        public static string Machine_Maintenance_Title_Delete_Machine_Maintenance {
            get {
                return ResourceManager.GetString("Machine_Maintenance_Title_Delete_Machine_Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Machine Form.
        /// </summary>
        public static string Machine_Maintenance_Title_Edit_Machine_Maintenance {
            get {
                return ResourceManager.GetString("Machine_Maintenance_Title_Edit_Machine_Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Detail.
        /// </summary>
        public static string Machine_Maintenance_Title_Machine_Maintenance_Detail {
            get {
                return ResourceManager.GetString("Machine_Maintenance_Title_Machine_Maintenance_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Lists.
        /// </summary>
        public static string Machine_Maintenance_Title_Machine_Maintenance_Lists {
            get {
                return ResourceManager.GetString("Machine_Maintenance_Title_Machine_Maintenance_Lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Maintenance user.
        /// </summary>
        public static string Maintenance_User {
            get {
                return ResourceManager.GetString("Maintenance_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance User.
        /// </summary>
        public static string Maintenance_User_Name {
            get {
                return ResourceManager.GetString("Maintenance_User_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM Configuration.
        /// </summary>
        public static string PM_Configuration {
            get {
                return ResourceManager.GetString("PM_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient Email.
        /// </summary>
        public static string Receipent_Email {
            get {
                return ResourceManager.GetString("Receipent_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Date is required, must be greater than today&apos;s date.
        /// </summary>
        public static string Schedule_Date {
            get {
                return ResourceManager.GetString("Schedule_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Date.
        /// </summary>
        public static string Schedule_Date_Name {
            get {
                return ResourceManager.GetString("Schedule_Date_Name", resourceCulture);
            }
        }
    }
}
