//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceSOPManifest {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceSOPManifest() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("REIN_MES_System.App_LocalResources.ResourceSOPManifest", typeof(ResourceSOPManifest).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding the Manifest record failed.Please Try Again.
        /// </summary>
        public static string Manifest_Add_Failure {
            get {
                return ResourceManager.GetString("Manifest_Add_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Added Manifest .
        /// </summary>
        public static string Manifest_Add_Success {
            get {
                return ResourceManager.GetString("Manifest_Add_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbUpdateException Occurred while Creating Manifest.
        /// </summary>
        public static string Manifest_Create_DbUpdateException {
            get {
                return ResourceManager.GetString("Manifest_Create_DbUpdateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Occurred while Creating Manifest.
        /// </summary>
        public static string Manifest_Create_Exception {
            get {
                return ResourceManager.GetString("Manifest_Create_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Delete Manifest record because it is has dependency in other modules.
        /// </summary>
        public static string Manifest_Delete_Dependency_Failure {
            get {
                return ResourceManager.GetString("Manifest_Delete_Dependency_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the Manifest record failed.Please Try Again.
        /// </summary>
        public static string Manifest_Delete_Failure {
            get {
                return ResourceManager.GetString("Manifest_Delete_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Deleted the Manifest Record.
        /// </summary>
        public static string Manifest_Delete_Success {
            get {
                return ResourceManager.GetString("Manifest_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbEntityValidationException Occurred while Editing Manifest.
        /// </summary>
        public static string Manifest_Edit_DbEntityValidationException {
            get {
                return ResourceManager.GetString("Manifest_Edit_DbEntityValidationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbUpdateException Occurred while Editing Manifest.
        /// </summary>
        public static string Manifest_Edit_DbUpdateException {
            get {
                return ResourceManager.GetString("Manifest_Edit_DbUpdateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Occurred while Editing Manifest.
        /// </summary>
        public static string Manifest_Edit_Exception {
            get {
                return ResourceManager.GetString("Manifest_Edit_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing the Manifest record failed.Please Try Again.
        /// </summary>
        public static string Manifest_Edit_Falure {
            get {
                return ResourceManager.GetString("Manifest_Edit_Falure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Modified Manifest.
        /// </summary>
        public static string Manifest_Edit_Success {
            get {
                return ResourceManager.GetString("Manifest_Edit_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Upload a Part Image.
        /// </summary>
        public static string Manifest_Image_Required {
            get {
                return ResourceManager.GetString("Manifest_Image_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manifest Image.
        /// </summary>
        public static string Manifest_Image_Title {
            get {
                return ResourceManager.GetString("Manifest_Image_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Description.
        /// </summary>
        public static string Manifest_Part_Desc {
            get {
                return ResourceManager.GetString("Manifest_Part_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part No.
        /// </summary>
        public static string Manifest_PartNo_Label {
            get {
                return ResourceManager.GetString("Manifest_PartNo_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manifest Upload.
        /// </summary>
        public static string Manifest_Title_Add_Manifest {
            get {
                return ResourceManager.GetString("Manifest_Title_Add_Manifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Manifest.
        /// </summary>
        public static string Manifest_Title_Delete_Manifest {
            get {
                return ResourceManager.GetString("Manifest_Title_Delete_Manifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manifest Edit.
        /// </summary>
        public static string Manifest_Title_Edit_Manifest {
            get {
                return ResourceManager.GetString("Manifest_Title_Edit_Manifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manifest List.
        /// </summary>
        public static string Manifest_Title_Manifest_Lists {
            get {
                return ResourceManager.GetString("Manifest_Title_Manifest_Lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manifest Create.
        /// </summary>
        public static string ManifestCreateTitle {
            get {
                return ResourceManager.GetString("ManifestCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manifest.
        /// </summary>
        public static string ManifestTitle {
            get {
                return ResourceManager.GetString("ManifestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Code.
        /// </summary>
        public static string Model_Code {
            get {
                return ResourceManager.GetString("Model_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        public static string Model_Family {
            get {
                return ResourceManager.GetString("Model_Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding the SOP record failed.Please Try Again.
        /// </summary>
        public static string SOP_Add_Failure {
            get {
                return ResourceManager.GetString("SOP_Add_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Added SOP .
        /// </summary>
        public static string SOP_Add_Success {
            get {
                return ResourceManager.GetString("SOP_Add_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbUpdateException Occurred while Creating SOP.
        /// </summary>
        public static string SOP_Create_DbUpdateException {
            get {
                return ResourceManager.GetString("SOP_Create_DbUpdateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Occurred while Creating SOP.
        /// </summary>
        public static string SOP_Create_Exception {
            get {
                return ResourceManager.GetString("SOP_Create_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Delete SOP record because it is has dependency in other modules.
        /// </summary>
        public static string SOP_Delete_Dependency_Failure {
            get {
                return ResourceManager.GetString("SOP_Delete_Dependency_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the SOP record failed.Please Try Again.
        /// </summary>
        public static string SOP_Delete_Failure {
            get {
                return ResourceManager.GetString("SOP_Delete_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Deleted the SOP Record.
        /// </summary>
        public static string SOP_Delete_Success {
            get {
                return ResourceManager.GetString("SOP_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbEntityValidationException Occurred while Editing SOP.
        /// </summary>
        public static string SOP_Edit_DbEntityValidationException {
            get {
                return ResourceManager.GetString("SOP_Edit_DbEntityValidationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbUpdateException Occurred while Editing SOP.
        /// </summary>
        public static string SOP_Edit_DbUpdateException {
            get {
                return ResourceManager.GetString("SOP_Edit_DbUpdateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Occurred while Editing SOP.
        /// </summary>
        public static string SOP_Edit_Exception {
            get {
                return ResourceManager.GetString("SOP_Edit_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing the SOP record failed.Please Try Again.
        /// </summary>
        public static string SOP_Edit_Falure {
            get {
                return ResourceManager.GetString("SOP_Edit_Falure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Modified SOP.
        /// </summary>
        public static string SOP_Edit_Success {
            get {
                return ResourceManager.GetString("SOP_Edit_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Upload a SOP Image.
        /// </summary>
        public static string SOP_Image_Required {
            get {
                return ResourceManager.GetString("SOP_Image_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOP Image.
        /// </summary>
        public static string SOP_Image_Title {
            get {
                return ResourceManager.GetString("SOP_Image_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Code.
        /// </summary>
        public static string SOP_ModelCode {
            get {
                return ResourceManager.GetString("SOP_ModelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOP Name.
        /// </summary>
        public static string SOP_Name {
            get {
                return ResourceManager.GetString("SOP_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOP Name is required.
        /// </summary>
        public static string SOP_Name_Required {
            get {
                return ResourceManager.GetString("SOP_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOP Upload.
        /// </summary>
        public static string SOP_Title_Add_SOP {
            get {
                return ResourceManager.GetString("SOP_Title_Add_SOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete SOP.
        /// </summary>
        public static string SOP_Title_Delete_SOP {
            get {
                return ResourceManager.GetString("SOP_Title_Delete_SOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOP Edit.
        /// </summary>
        public static string SOP_Title_Edit_SOP {
            get {
                return ResourceManager.GetString("SOP_Title_Edit_SOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOP List.
        /// </summary>
        public static string SOP_Title_SOP_Lists {
            get {
                return ResourceManager.GetString("SOP_Title_SOP_Lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOP Create.
        /// </summary>
        public static string SOPCreateTitle {
            get {
                return ResourceManager.GetString("SOPCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOP.
        /// </summary>
        public static string SOPTitle {
            get {
                return ResourceManager.GetString("SOPTitle", resourceCulture);
            }
        }
    }
}
