//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceManagerConfig {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceManagerConfig() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("REIN_MES_System.App_LocalResources.ResourceManagerConfig", typeof(ResourceManagerConfig).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the plant code.
        /// </summary>
        public static string Manager_Error_Manager_Code_Required {
            get {
                return ResourceManager.GetString("Manager_Error_Manager_Code_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager name is already exists. Please try with other name.
        /// </summary>
        public static string Manager_Error_Manager_Name_Exists {
            get {
                return ResourceManager.GetString("Manager_Error_Manager_Name_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Manager name.
        /// </summary>
        public static string Manager_Error_Manager_Name_Required {
            get {
                return ResourceManager.GetString("Manager_Error_Manager_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Address.
        /// </summary>
        public static string Manager_Label_Manager_Address {
            get {
                return ResourceManager.GetString("Manager_Label_Manager_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Manager_Label_Manager_City {
            get {
                return ResourceManager.GetString("Manager_Label_Manager_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Code.
        /// </summary>
        public static string Manager_Label_Manager_Code {
            get {
                return ResourceManager.GetString("Manager_Label_Manager_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Manager_Label_Manager_Country {
            get {
                return ResourceManager.GetString("Manager_Label_Manager_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Name.
        /// </summary>
        public static string Manager_Label_Manager_Name {
            get {
                return ResourceManager.GetString("Manager_Label_Manager_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string Manager_Label_Manager_State {
            get {
                return ResourceManager.GetString("Manager_Label_Manager_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager is added successfully.
        /// </summary>
        public static string Manager_Success_Manager_Add_Success {
            get {
                return ResourceManager.GetString("Manager_Success_Manager_Add_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager is deleted successfully.
        /// </summary>
        public static string Manager_Success_Manager_Delete_Success {
            get {
                return ResourceManager.GetString("Manager_Success_Manager_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager is edited successfully.
        /// </summary>
        public static string Manager_Success_Manager_Edit_Success {
            get {
                return ResourceManager.GetString("Manager_Success_Manager_Edit_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Manager Form.
        /// </summary>
        public static string Manager_Title_Add_Manager {
            get {
                return ResourceManager.GetString("Manager_Title_Add_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Manager Form.
        /// </summary>
        public static string Manager_Title_Delete_Manager {
            get {
                return ResourceManager.GetString("Manager_Title_Delete_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Manager Form.
        /// </summary>
        public static string Manager_Title_Edit_Manager {
            get {
                return ResourceManager.GetString("Manager_Title_Edit_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Detail.
        /// </summary>
        public static string Manager_Title_Manager_Detail {
            get {
                return ResourceManager.GetString("Manager_Title_Manager_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Lists.
        /// </summary>
        public static string Manager_Title_Manager_Lists {
            get {
                return ResourceManager.GetString("Manager_Title_Manager_Lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Site_Variable_Add {
            get {
                return ResourceManager.GetString("Site_Variable_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Site_Variable_Create {
            get {
                return ResourceManager.GetString("Site_Variable_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Site_Variable_Index {
            get {
                return ResourceManager.GetString("Site_Variable_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists.
        /// </summary>
        public static string Site_Variable_Lists {
            get {
                return ResourceManager.GetString("Site_Variable_Lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managers.
        /// </summary>
        public static string Site_Variable_Manager {
            get {
                return ResourceManager.GetString("Site_Variable_Manager", resourceCulture);
            }
        }
    }
}
