//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REIN_MES_System.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMainFeederMapping {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMainFeederMapping() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("REIN_MES_System.App_LocalResources.ResourceMainFeederMapping", typeof(ResourceMainFeederMapping).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy Meter Master.
        /// </summary>
        public static string MainFeeder_List {
            get {
                return ResourceManager.GetString("MainFeeder_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbUpdateException Occurred while Creating Main meter Mapping.
        /// </summary>
        public static string MainFeederMapping__Create_DbUpdateException {
            get {
                return ResourceManager.GetString("MainFeederMapping__Create_DbUpdateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbEntityValidationException Occurred while Editing Main meter Mapping.
        /// </summary>
        public static string MainFeederMapping__Edit_DbEntityValidationException {
            get {
                return ResourceManager.GetString("MainFeederMapping__Edit_DbEntityValidationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbUpdateException Occurred while Editing Main meter Mapping.
        /// </summary>
        public static string MainFeederMapping__Edit_DbUpdateException {
            get {
                return ResourceManager.GetString("MainFeederMapping__Edit_DbUpdateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Delete the Main meter Mapping record because it is has dependency in other modules.
        /// </summary>
        public static string MainFeederMapping_Delete_Dependency_Failure {
            get {
                return ResourceManager.GetString("MainFeederMapping_Delete_Dependency_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Feeder (Meter) Mapping is  config added successfully.
        /// </summary>
        public static string MainFeederMapping_Success_MainFeederMapping_Add_Success {
            get {
                return ResourceManager.GetString("MainFeederMapping_Success_MainFeederMapping_Add_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Feeder (Meter)Mapping is  config deleted successfully.
        /// </summary>
        public static string MainFeederMapping_Success_MainFeederMapping_Delete_Success {
            get {
                return ResourceManager.GetString("MainFeederMapping_Success_MainFeederMapping_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Feeder (Meter )Mapping is  edited  successfully.
        /// </summary>
        public static string MainFeederMapping_Success_MainFeederMapping_edit_Success {
            get {
                return ResourceManager.GetString("MainFeederMapping_Success_MainFeederMapping_edit_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy Meter Master.
        /// </summary>
        public static string Title_Add_MainFeeder {
            get {
                return ResourceManager.GetString("Title_Add_MainFeeder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy Meter Master.
        /// </summary>
        public static string Title_Edit_MainFeeder {
            get {
                return ResourceManager.GetString("Title_Edit_MainFeeder", resourceCulture);
            }
        }
    }
}
